### ISSUE TITLE
(bed) error on dual indexed 10x data

### ISSUE THREAD

**Issue by micans** [wheaton5/souporcell#103]
Hello, we have this data:
10X 3’ Gene Expression v3.1 Libraries samples: with each sample being a multiplexed pool of 3 patients' (human) tissues (total 6 patients). This new 10X kit makes use of dual indexing.

We got the following error for all of our 12 samples (one shown):
```
***** WARNING: File soc/depth_merged.bed has inconsistent naming convention for record:
KI270728.1  19626 19638

***** WARNING: File soc/depth_merged.bed has inconsistent naming convention for record:
KI270728.1  19626 19638

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 563, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 509, in doublets
    subprocess.check_call(["troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['troublet', '--alts', 'soc/alt.mtx', '--refs', 'soc/ref.mtx', '--clusters', 'soc/clusters_tmp.tsv']'
 returned non-zero exit status 101.
 ```
 
I am not sure whether the following may have an impact, but I've noticed that for the recent dual gex/ATAC data the `possorted_bam.bam` file has changed chromosome sorting compared to what cellranger  produced before, and the same is true for the possorted_genome_bam.bam in these cellranger outputs. It now gives

```
[farm5-head1] [..a/asampleid] [] samtools view -H possorted_genome_bam.bam | head
@HD	VN:1.4	SO:coordinate
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr10	LN:133797422
@SQ	SN:chr11	LN:135086622
@SQ	SN:chr12	LN:133275309
```

whereas previously it would use human version sorting (I'm pretty sure). I don't quite see how the error message comes into it, but I thought I'd mention it. I haven't pulled the latest image yet and admittedly our image is dated Apr 2  2020. However, that image has been working fine for a number of analyses. I'll pull the latest image and test that too.

**Comment by wheaton5** [comment]
Hi Stjin, its been a while. Hope you are doing well.

The retagging/remapping process is not updated for dual tagging. I think it might work if you use the --skip_remap True and --common_variants option (download the 1000k genomes common variants vcf from the souporcell github page). Let me know.

**Comment by micans** [comment]
Hi Haynes,

thanks for the quick response! As you say, it's been a while. We have resubmitted the jobs. Incidentally I find this new sorting of chromosome names a bit surprising. It shouldn't matter of course and I'm glad it doesn't with soc. We get regular requests for it, so thanks for the great software _and_ support. I am keeping well. Hope you do too (on the other side of the pond?).

**Comment by micans** [comment]
Hello, the problem re-occurred. Going into the soc execution directory, it seems nothing is found and everything is empty:

```
-rw-rw-r--+ 1 user-su user 102689244 Feb 26 17:32 depth_merged.bed
-rw-rw-r--+ 1 user-su user         0 Feb 26 17:32 common_variants_covered_tmp.vcf
-rw-rw-r--+ 1 user-su user        32 Feb 26 17:33 variants.done
-rw-rw-r--+ 1 user-su user      2163 Feb 26 17:33 common_variants_covered.vcf
-rw-rw-r--+ 1 user-su user         0 Feb 26 17:33 vartrix.done
-rw-rw-r--+ 1 user-su user        73 Feb 26 17:33 ref.mtx
-rw-rw-r--+ 1 user-su user        73 Feb 26 17:33 alt.mtx
-rw-rw-r--+ 1 user-su user    480654 Feb 26 17:33 clusters_tmp.tsv
-rw-rw-r--+ 1 user-su user     26809 Feb 26 17:33 clusters.err
-rw-rw-r--+ 1 user-su user         0 Feb 26 17:33 clustering.done
-rw-rw-r--+ 1 user-su user       207 Feb 26 17:33 doublets.err
-rw-rw-r--+ 1 user-su user        89 Feb 26 17:33 clusters.tsv
```
The `vcf` and `mtx` files only have headers, no data. The file `cluster_tmp.tsv` has all lines looking like this:

```
AAACCCAAGGGCTAAC-1	0	-1.0986123	-1.0986123	-1.0986123
AAACCCACACAACCGC-1	0	-1.0986123	-1.0986123	-1.0986123
AAACCCACATGGGTCC-1	0	-1.0986123	-1.0986123	-1.0986123
AAACCCAGTAACAGTA-1	0	-1.0986123	-1.0986123	-1.0986123
```

We use the fasta file `refdata-gex-GRCh38-2020-A/fasta/genome.fa` from cellranger (might there be an issue there?).
Our command line:

```
singularity exec -B /lustre -B /nfs \
      $im souporcell_pipeline.py \
      -i $psb                 \
      -b $bcd                 \
      -f $fa                  \
      -k $thek                \
      --common_variants $cv   \
      -t $CPU -o soc          \
      --skip_remap True
```
The STDOUT is:

```
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory soc
using common variants
4
running vartrix
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 3 -a soc/alt.mtx -r soc/ref.mtx --restarts 100 -b barcodes.tsv --min_ref 4 --min_alt
4 --threads 4
running souporcell doublet detection
```

Let me know if any further information would be useful. I have checked whether I made some sort of oversight but will continue to do so.

Thanks,
Stijn

**Comment by wheaton5** [comment]
check the chromosome naming convention between the vcf, fasta, and bam. I'm not sure if a difference in sorting order would be a problem or not.

**Comment by micans** [comment]
The fasta and bam agree and have alphabetic sorting (to my mind weirdly):

```
>chr1 1
>chr10 10
>chr11 11
>chr12 12
>chr13 13
>chr14 14
>chr15 15
>chr16 16
>chr17 17
>chr18 18
>chr19 19
>chr2 2
>chr20 20
>chr21 21
>chr22 22
>chr3 3
>chr4 4
>chr5 5
>chr6 6
>chr7 7
>chr8 8
>chr9 9
>chrM MT
>chrX X
>chrY Y
```
The vcf file has natural order, chr1 chr2 chr3 etc.
I see Picard has `SortVcf` tool. I can give that or something else a go to resort the vcf file.

**Comment by wheaton5** [comment]
also make sure to delete the output directories between runs if it has gone poorly. It tries to dynamically reuse previously unfinished pipelines, but if they just made bad output that wont work.

**Comment by micans** [comment]
Yes we did remove the output directories - we got caught by that but remedied it, so that's not the issue here I think. Is it conceivable that the different sort orders would lead to zero variants found (in `common_variants_covered.vcf`)?

**Comment by wheaton5** [comment]
bedtools intersect probably requires same sorting between the bed and the vcf. you can look at the sorting of depth_merged.bed.

**Comment by wheaton5** [comment]
huh, the docs say it doesnt have to be same sorting unless using the --sorted option. Can we take a quick look at that bedfile? like both the sorting and just how much of the genome it covers? if that bed file is okay then it has to be the intersect that is the problem.

**Comment by micans** [comment]
So for a summary of that file:
```
[farm5-head1] [.._c9ALS9490685/soc] [] cut -f 1 depth_merged.bed | uniq -c | head -n 20
 394916 chr1
 214686 chr10
 220251 chr11
 232527 chr12
 128679 chr13
 152832 chr14
 150748 chr15
 137527 chr16
 158460 chr17
 108701 chr18
 117379 chr19
 385790 chr2
  97482 chr20
  51452 chr21
  65607 chr22
 335777 chr3
 253392 chr4
 282332 chr5
 265442 chr6
 280942 chr7
```

**Comment by micans** [comment]
I've resorted the vcf file and am running an analysis with that. In both sort orders chromosome 1 is first, so naively I'd expect something for chromosome 1. Anyway, will update when it finishes or halts.

**Comment by micans** [comment]
Hello, pretty sure the issue is this:

The chromosome naming in that fasta file (`refdata-gex-GRCh38-2020-A/fasta/genome.fa`) uses `chr1` etc. Previously (e.g. `refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa`) this was `1` for other/earlier cellranger reference data. The vcf file has `1` etc. This explains why it now stopped working. I ran a `bedtools intersect` with a modified vcf file and that gave normal output (1961827 lines).

In the release notes (https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build, References - 2020-A (July 8, 2020)) there is some mention of changing from `1` to `chr1`. Perhaps that should not have been run or somehow I'm frazzled - I'll check with our facility what's what.

**Comment by micans** [comment]
Hi Haynes,

Of course this now ran to completion. I tested with remapping, and this gave a result as well, with good consistency with no remapping (see below). Is there any reason to prefer `--skip_remap True` (given the dual indexing)? For one sample, the two biggest clusters from remapped analysis look like this, when projected onto the clusters from cellranger-mapped data:

```
[farm5-head2] [..9490687/soc-remap] [] grep -Fwf <(tail -n +2 clusters.tsv | cut -f 1,3 | grep $'\t0$' | cut -f 1) ../soc2/clusters.tsv | cut -f 3 | sort | uniq -c
   3291 1
     14 1/0
     16 1/2
[farm5-head2] [..9490687/soc-remap] [] grep -Fwf <(tail -n +2 clusters.tsv | cut -f 1,3 | grep $'\t1$' | cut -f 1) ../soc2/clusters.tsv | cut -f 3 | sort | uniq -c
   4528 0
     20 0/1
     10 0/2
      1 1/0
```

**Comment by wheaton5** [comment]
I guess not. I thought there might be an issue, but if the cellranger dealt with the barcodes from the reads and just put them in the bam in the normal format then it should work fine without --skip_remap True.
