### ISSUE TITLE
Request: Please update the Singularity containers to Singularity-Hub

### ISSUE THREAD

**Issue by Zethson** [wheaton5/souporcell#106]
Hey,

I recently had an issue and you helped me solve it and it's working great now! Thank you.
On another note, please upload the container to Singularity-Hub: https://singularity-hub.org/
Just like Dockerhub, this is the place where people share containers. They are not distributed via Google drive for many reasons among them security. Many clusters don't even permit any traffic to Google for good reasons.

Thanks!
Cheers

**Comment by wheaton5** [comment]
Trying to make a build there. Will test it out and then update the readme if it works. Thanks for the suggestion.

**Comment by Zethson** [comment]
@wheaton5 Great, thank you. Feel free to ask if you need help.

**Comment by wheaton5** [comment]
done, forgot to close this
