### ISSUE TITLE
Far fewer barcodes in clusters.tsv than input

### ISSUE THREAD

**Issue by Zethson** [wheaton5/souporcell#108]
Hi,

I have a dataset with 13589760 barcodes which I used as input for Souporcell. However, Souporcell returns only 9030 rows × 11 columns. Therefore, I get far fewer barcodes and cannot assign a cluster to every barcode.

Am I missing something?

Thank you very much!

**Comment by wheaton5** [comment]
Well this should fail and not give you output really. Your data may have that many barcodes but not that many cells. Souporcell is meant to take in the barcodes.tsv from the output of cellranger which is just the barcodes that contained cells. I hope this helps.

**Comment by Zethson** [comment]
> Well this should fail and not give you output really. Your data may have that many barcodes but not that many cells. Souporcell is meant to take in the barcodes.tsv from the output of cellranger which is just the barcodes that contained cells. I hope this helps.

Yeah, I did use the barcodes.tsv as output from cellranger. Then I'll have to see why my data has this many barcodes.

Thanks!

**Comment by Zethson** [comment]
Just for reference: I didn't use the filtered, but the raw data. The filtered data has the expected amount of cells.
