### ISSUE TITLE
bedtools permission error in singularity

### ISSUE THREAD

**Issue by ktpolanski** [wheaton5/souporcell#11]
Hello,

Thank you for the fantastic tool and cohesive setup instructions. I set up singularity and figured I'd take the thing for a spin on the test data: `singularity exec souporcell.sif souporcell_pipeline.py -i A.merged.bam -b GSM2560245_barcodes.tsv -f ~/cellranger/GRCh38/fasta/genome.fa -t 8 -o demux_data_test -k 4 --skip_remap True --common_variants filtered_2p_1kgenomes_GRCh38.vcf`

Unfortunately, it seems to snag for whatever reason:

	imports done
	checking bam for expected tags
	checking fasta
	using common variants
	Traceback (most recent call last):
	  File "/opt/souporcell/souporcell_pipeline.py", line 436, in <module>
		final_vcf = freebayes(args, bam, fasta)
	  File "/opt/souporcell/souporcell_pipeline.py", line 249, in freebayes
		subprocess.check_call(["bedtools", "merge", "-i", args.out_dir + "/depth.bed"], stdout = bed)
	  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 306, in check_call  
		retcode = call(*popenargs, **kwargs)
	  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 287, in call
		with Popen(*popenargs, **kwargs) as p:
	  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 729, in __init__
		restore_signals, start_new_session)
	  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 1364, in _execute_child
		raise child_exception_type(errno_num, err_msg, err_filename)
	PermissionError: [Errno 13] Permission denied: 'bedtools'

Some assistance please? Any idea what's going on here?

**Comment by wheaton5** [comment]
I see what is going on and have reproduced the error. I need to build a new container. Will post here when done.

**Comment by wheaton5** [comment]
New container at
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1woFmL_twfOEKxBSKuF5-yWfoCF1uxn9d' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1woFmL_twfOEKxBSKuF5-yWfoCF1uxn9d" -O souporcell.sif && rm -rf /tmp/cookies.txt
```
I have run just singularity exec souporcell.sif bedtools --version and no longer get that error, but am running the full test in case other things come up.

Another note is that you will need to give it the hg19 fasta as well because it uses the fasta file to figure out how to chunk things and if the chroms/lengths are different it will break. I should have this check earlier and error out.

**Comment by ktpolanski** [comment]
Thanks for the quick turnaround!

I do give it a fasta, but of a GRCh38 variety, matching what you do in the demo in the readme. I get the matching GRCh38 common variants. Does it somehow need both that and hg19?

**Comment by wheaton5** [comment]
Well in my example I don't use --skip_remap or --common_variants.

When not using --common_variants I don't recommend using --skip_remap. So in that setup it will first remap to the fasta reference you give it using minimap2 (which produces alignments better for variant calling). So while the A.merged.bam is mapped to hg19, the remapping maps it to whatever fasta you give it.

Basically in --skip_remap and --common_variants, you will need the common variants vcf and the reference fasta be the same reference that the bam is mapped to. In this case, that is hg19.

**Comment by ktpolanski** [comment]
Ahh, okay, did not know that it was mapped to hg19 to start. Thanks for the heads up.

**Comment by wheaton5** [comment]
closing this issue, feel free to reopen if you have issues.

**Comment by ktpolanski** [comment]
Managed to get it to finish, encountered a few vartrix hiccups. It requires the BAM and genome FASTA to both be indexed. Should be easy to add to the pipeline.

However, I now have a different question. Seeing how in my use case there will be multiple 10X samples with the same donors, I'll have to match the clusters souporcell identifies across runs. I opened up `cluster_genotypes.vcf` to see how to go about this, and was met with this sort of numerical jumble in the four cluster-specific columns:

	1/1:2:0:-1:-4:-9,-1,-2:-8,0,-1	1/1:1:0:-1:-4:-5,-1,-1:-4,0,-1	./.:0:0:-1:-4:-1,-1,-1:-1,-1,-1	./.:0:0:-1:-4:-1,-1,-1:-1,-1,-1
	1/1:2:0:-1:-4:-9,-1,-2:-8,0,-1	1/1:1:0:-1:-4:-5,-1,-1:-4,0,-1	./.:0:0:-1:-4:-1,-1,-1:-1,-1,-1	./.:0:0:-1:-4:-1,-1,-1:-1,-1,-1
	./.:0:0:0:-3:-1,-1,-1:-1,-1,-1	./.:0:0:0:-3:-1,-1,-1:-1,-1,-1	1/1:2:0:0:-3:-9,-1,-2:-8,0,-1	./.:0:0:0:-3:-1,-1,-1:-1,-1,-1
	./.:0:0:-1:-5:-1,-1,-1:-1,-1,-1	0/0:0:1:-1:-5:-1,-5,-1:0,-5,-1	1/1:1:0:-1:-5:-5,-1,-1:-5,0,-1	./.:0:0:-1:-5:-1,-1,-1:-1,-1,-1
	0/0:0:28:-31:-60:-1,-116,-20:0,-114,-18	0/0:0:2523:-31:-60:-26,-10357,-1708:0,-10330,-1682	0/0:0:19:-31:-60:-1,-79,-13:0,-77,-12	0/0:1:32:-31:-60:-2,-128,-19:0,-126,-17

How do I interpret this? A gut response would be to look at the pre-slash symbols: `1` as present, but then why are there both `0` and `.` as alternatives? I tried to decipher what's going on here based on the source code in `consensus.py`, but didn't have a ton of luck. I'm essentially trying to end up with a list of SNPs per cluster, I feel like this set of columns is the correct place to be looking?

**Comment by wheaton5** [comment]
This should be in proper vcf format. So The format field (what you are looking at) is governed by the preceding field which should read GT:AO:RO:T:E:GO:GN. Okay all of this is very round about, but each of those is defined in the header. 

What it boils down to is that separators are the ':' character and the first one (0/0 or 1/1 or 0/1 or ./.) is the genotype call. But I see here that it is being very aggressive with these calls. I should tighten that up, anyway. The next two fields are AO (alt alleles observed) and RO (ref alleles observed).

You should also pay attention to the filter field which is the 7th column in the file. If that has anything other than . or PASS, consider that a filtered variant. 

I have considered this use case and should make some software for matching clusters across samples, but haven't gotten around to it. At the moment, I have several other pending things so don't expect this within the next week, but it is on my list. Sorry

**Comment by ktpolanski** [comment]
All good, I'm happy to do it myself. Your answer should be perfectly sufficient for me to do it. Thanks!
