### ISSUE TITLE
Input matrices to troublet

### ISSUE THREAD

**Issue by senbaikang** [wheaton5/souporcell#113]
Hi @wheaton5,

I was trying to run souporcell and troublet on some data. I noticed that troublet requires matrices for alternative and reference counts, respectively. Are these two matrices the same as the inputs to souporcell in the previous step? If no, could you please explain the difference briefly? If yes, I actually encountered a bug from troublet which states 'allele matrices do not match' (line 320 in the source code). I might be wrong, but for me in this case requiring the same locus and cell index does not make much sense as they are sparse matrices. Could you please help me with it?

**Comment by wheaton5** [comment]
Is there a reason you are trying to run this outside of the pipeline?

The matrices are the same for both, and should match as they are output by vartrix in such a way that they will have all of the same entries, but may have 0 values for one and non zero for the other.

But I have run into issues in troublet when people give it the raw barcodes.tsv instead of just the cell barcodes. I have some assumptions in the code that are broken when cells have no alleles.

**Comment by senbaikang** [comment]
Thank you for the quick reply!

I am running it out of pipeline because I am testing different tools on some simulated data generated directly in `.mtx` format.

I think I ran into a similar issue in troublet to what you mentioned above. I pinpointed the problem at:

https://github.com/wheaton5/souporcell/blob/1bd9f11d70eaee6ac14713de09c377c285ca2787/troublet/src/main.rs#L320

as well as 

https://github.com/wheaton5/souporcell/blob/1bd9f11d70eaee6ac14713de09c377c285ca2787/troublet/src/main.rs#L323
.

From my understanding, these two lines require the coordinate, `(locus, cell index)`, of two entries with the same line index in the alternative and reference input matrices being the same. But since the matrices are sparse, it actually impossible to have such a limit. Could you please have a look at it?

**Comment by wheaton5** [comment]
if vartrix is run with --scoring-method coverage then the matrices should match

**Comment by wheaton5** [comment]
they should have the same number of lines, but some entries will be 0 entries. if neither ref nor alt have any coverage then the locus will not appear in either output file. if it occurs in one and not the other, it will show up in both but be a 0 in one

**Comment by senbaikang** [comment]
Now I understand. Thank you very much for your help!
