### ISSUE TITLE
Support for Python 3.7+

### ISSUE THREAD

**Issue by yihming** [wheaton5/souporcell#121]
Hello,

When reading through the Singularity file of the repo, as well as `souporcell_env.yaml`, I noticed that all the Python dependencies were installed within a Python 3.6 environment. I'm wondering if the Python version matters here. Is it okay to use a later version, e.g. Python 3.7, instead?

Thanks!

Sincerely,
Yiming

**Comment by wheaton5** [comment]
You are free to try it of course. I find that the pystan package is very sensitive to the python version and the consensus genotype calling and ambient RNA estimation step may fail. If you only need clustering + doublet calling outputs, then it shouldn't be a problem.

**Comment by yihming** [comment]
Thank you for sharing this information!
