### ISSUE TITLE
Barcoded from cellranger v6 (barcodes.tsv.gz) as FileNotFoundError:

### ISSUE THREAD

**Issue by sanchezy** [wheaton5/souporcell#123]
Hi, 
I would like to use souporcell for analysing my single-cell data. I managed to run the example (demux data set) but when tried with my data I get the error:
"No such file or directory: '/home/Sample1/outs/filtered_feature_bc_matrix/barcodes.tsv.gz'. 

Should I unzip all barcodes.tsv.gz files? 

Many thanks,

**Comment by domenico-somma** [comment]
Hi,
I think I have the same issue:

```
$ singularity exec souporcell_latest.sif souporcell_pipeline.py -i /data/Dom/souporcell/E1_2114/possorted_genome_bam.bam -b /data/Dom/souporcell/E1_2114/barcodes.tsv.gz -f /data/Dom/souporcell/E1_2114/genome.fa -t 30 -o results_test -k 2

checking modules
imports done
checking bam for expected tags
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 64, in <module>
    with open_function(args.barcodes) as barcodes:
  File "/opt/souporcell/souporcell_pipeline.py", line 57, in <lambda>
    open_function = lambda f: gzip.open(f,"rt") if f[-3:] == ".gz" else open(f)
  File "/usr/local/envs/py36/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/envs/py36/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/Dom/souporcell/E1_2114/barcodes.tsv.gz'
```

but mine should come from CellRanger3, not 6. I tried as well zipped/unzipped but doesn't work.
Any workaround?

Thanks!

**Comment by domenico-somma** [comment]
Hi, I solved binding the path to singularity with `--bind` parameter

ref: https://sylabs.io/guides/3.7/user-guide/bind_paths_and_mounts.html

Thanks

**Comment by sanchezy** [comment]
Hi @domenico-somma. Thanks for sharing this. I read the documentation but it is no clear to me what the container directory I should use. Could you please share the command you used to run this? 
Many thanks in advance!

**Comment by domenico-somma** [comment]
Hi @sanchezy, depend on where you have your data. From your error should be something like:

`singularity exec --bind /home souporcell_latest.sif souporcell_pipeline.py ....`

**Comment by wheaton5** [comment]
I just make sure all data is downstream in the file system (so in the directory from which u run it or in subdirectories).

**Comment by sanchezy** [comment]
Hi, 
The solution for me was to amend the bindpath as well. In the cluster I am using, I needed to add my /Scratch directory. So, I added to my .bashrc profile the following:

```
# Set all the Singularity cache dirs to Scratch
export SINGULARITY_CACHEDIR=$HOME/Scratch/.singularity
export SINGULARITY_TMPDIR=$SINGULARITY_CACHEDIR/tmp
export SINGULARITY_LOCALCACHEDIR=$SINGULARITY_CACHEDIR/localcache
export SINGULARITY_PULLFOLDER=$SINGULARITY_CACHEDIR/pull

# Bind your Scratch directory so it is accessible from inside the container
#      and the temporary storage jobs are allocated
export SINGULARITY_BINDPATH=/scratch/scratch/$USER,/tmpdir
```

**Comment by daccachejoe** [comment]
Hi - I wanted to reopen this as this error has just resurfaced in my analysis. I have run the pipeline successfully in the past and haven't changed my script at all but not it cannot open `barcodes.tsv.gz`. I have tried upgrading to the newest version of the package and the error persists. Here is my code
```
singularity exec --bind /gpfs/home/jd5457/scherlink/multiome-pso-twin-pbmc/souporcell/JOSC01_NYUPsoriasispool1_1_v1 \
    souporcell_latest.sif souporcell_pipeline.py \
    -i gex_possorted_bam.bam \
    -b barcodes.tsv.gz \
    -t 24 \
    -f genome.fa \
    -k 4 \
    --known_genotypes filtered_merged_genotypes.vcf \
    --known_genotypes_sample_names ${sample_names[@]} \
    -o ./out_gex
```

And the error message
```
source: open /gpfs/home/jd5457/activate: no such file or directory

CondaError: Run 'conda init' before 'conda activate'

checking modules
imports done
checking bam for expected tags
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 65, in <module>
    with open_function(args.barcodes) as barcodes:
  File "/opt/souporcell/souporcell_pipeline.py", line 57, in <lambda>
    open_function = lambda f: gzip.open(f,"rt") if f[-3:] == ".gz" else open(f)
  File "/miniconda3/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/miniconda3/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'barcodes.tsv.gz'
```

The conda error is new to the newest package version and was not the case on the old version of souporcell (I downloaded the old version on August 2023).

**Comment by wheaton5** [comment]
Sometimes singularity needs you to bind directories even the current working directories. Cant remember the option, but i think that is the issue

**Comment by daccachejoe** [comment]
I don't know singularity well enough to know why this works but adding the `--no-home` flag to the function call solved my problem. I assume my HPC updated the singularity defaults in some way that caused the change from previous times this worked. 
```
singularity exec --no-home --bind /path/to/directory \
souporcell_latest.sif souporcell_pipeline.py [all the options]
```
