### ISSUE TITLE
Conda / bioconda package

### ISSUE THREAD

**Issue by chris-rands** [wheaton5/souporcell#131]
I notice you have a suggestion for installing from github and building a conda environment, but is there any plan to make souporcell available on conda or bioconda directly? Thanks

**Comment by wheaton5** [comment]
I will look into this. I haven't done this before. Thanks for the suggestion.

**Comment by Zethson** [comment]
Dear @wheaton5 

we're interested in a Bioconda package for the https://github.com/theislab/hadge pipeline. I see that you closed this issue as completed but I cannot find Souporcell on Bioconda.
Would it be possible to reopen this issue or could you point us towards where the Conda package lives?

We might be able to help with the Conda recipe if required.

Thank you!

CC @Emiller88

**Comment by mfansler** [comment]
We now have it built on Bioconda for `linux-64`. Since it orchestrates many packages, I recommend keeping it in a dedicated environment, e.g., 

```bash
conda create -n souporcell_2_5 -c conda-forge -c bioconda souporcell=2.5
```

If any issues arise with it, feel free to ping me.
