### ISSUE TITLE
pyfaidx.FastaNotFoundError: Cannot read FASTA file

### ISSUE THREAD

**Issue by gebdu** [wheaton5/souporcell#142]
..>> Fasta file is there. and it is the same fasta file I used for CellRanger mapping:

$ singularity exec $sif/souporcell_latest.sif souporcell_pipeline.py -i $bm/possorted_genome_bam.bam -b $bc/barcodes.tsv -f $ref/genome.fa -t 16 -o demux_data_test -k 2

WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check" "storage.options.thinpool.ostree_repo" "storage.options.thinpool.skip_mount_home"] from "/etc/containers/storage.conf". 

checking modules
imports done
checking bam for expected tags
checking fasta
Traceback (most recent call last):
  File "/usr/local/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 370, in __init__
    if mutable else 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data2/CellRanger/REFERENCE/hg19/hg19/fasta/genome.fa'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 109, in <module>
    fasta = pyfaidx.Fasta(args.fasta, key_function = lambda key: key.split()[0])
  File "/usr/local/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 1011, in __init__
    build_index=build_index)
  File "/usr/local/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 379, in __init__
    "Cannot read FASTA file %s" % filename)
pyfaidx.FastaNotFoundError: Cannot read FASTA file /data2/CellRanger/REFERENCE/hg19/hg19/fasta/genome.fa

# head  /data2/CellRanger/REFERENCE/hg19/hg19/fasta/genome.fa
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1 REF
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

So,fasta is there, but why it is unable to read?

**Comment by Boroviak-Lab** [comment]
Hi @gebdu what was the fix for this? Seeing the same thing at the moment.
