### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Giov12** [wheaton5/souporcell#149]
Hello. I just downloaded souporcell a few days ago using singularity. When I try to run the container, I get an import error for one of the python modules. Is there a recommended way to get around this? Thank you.

**Comment by wheaton5** [comment]
Im not sure how this is possible but im working on a new singularity build. And u can do manual install as well. Sorry about this

**Comment by Giov12** [comment]
Just in case anyone else has this issue, the issue was that souporcell was using my working directory's python environment. Since I work on a remote cluster, I ended up using a virtual environment that contained all the python dependencies.

**Comment by Giov12** [comment]
Just in case anyone else has this issue, the issue was that souporcell was using my working directory's python environment. Since I work on a remote cluster, I ended up using a virtual environment that contained all the python dependencies.
