### ISSUE TITLE
Consensus VCF writing fails if done in parallel for multiple files

### ISSUE THREAD

**Issue by royoelen** [wheaton5/souporcell#15]
I am trying to create multiple VCF files by submitting the Souporcell consensus creations as jobs on our cluster. Some of these jobs however run in parallel, and at that point the consensus VCF creation step fails.

I believe this is due to them writing/reading/removing the same temporary file: "tempsouporcell.vcf" (perhaps prepend/append timestamp+generated random string?)

This is not a huge issue as the consensus creation is pretty quick so it can be done in sequence for multiple files, but limits our automation by just a little bit

**Comment by wheaton5** [comment]
I am confused. Are you using the souporcell_pipeline or are you doing the steps separately by yourself? If the former, each pipeline should be given a different output directory. If the latter, can you elaborate exactly what you are running? You could bypass this yourself by making a new directory for each job and running from that working directory. Still, I could improve this on my end. Just trying to think of ways to get you unstuck as fast as possible.

**Comment by royoelen** [comment]
I am running the steps separately (no other way on our cluster unfortunately), and am outputting them to the same folder. I am not really stuck, as I can just run the files in sequence. So no big issue on my end.

**Comment by wheaton5** [comment]
You should be able to submit the pipeline to the cluster. Just have to request the number of threads you give the pipeline for the job. What job manager are you using (eg sge, lsf, slurm)? This is how I run it on our cluster. Then if you have multiple pipelines, those would be separate cluster jobs with separate output directories.
