### ISSUE TITLE
error when running with --common_variants

### ISSUE THREAD

**Issue by ste-depo** [wheaton5/souporcell#153]
Hi everybody,

when I try to give a vcf file to the pipeline containing my preferred variants (this file - souporcell_merged_sorted_vcf.vcf.gz - was calculated earlier by souporcell_pipeline.py from another sample of my analysis), I got the following warning (at the beginning of the pipeline):

```
***** WARNING: File /mnt/soup_or_cell/depth_merged.bed has inconsistent naming convention for record:
JH584299.1      377148  377170
***** WARNING: File /mnt/soup_or_cell/depth_merged.bed has inconsistent naming convention for record:
JH584299.1      377148  377170
```

And the following error (at the end of the pipeline):

```
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 584, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/opt/souporcell/souporcell_pipeline.py", line 400, in freebayes
    for line in common:
  File "/usr/local/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

Do you have any clue about this?

All the best!
Stefano

**Comment by wheaton5** [comment]
Looks like my common variants argument doesnt support gzipped vcfs currently. I should change that, but for now you can just gunzip it.

**Comment by ste-depo** [comment]
Okay. Also, the other output file of the pipeline (cluster_genotypes.vcf) might be used instead, which is already gunzipped.

Thanks a lot
