### ISSUE TITLE
Inbred individuals treated as doublets?

### ISSUE THREAD

**Issue by imillercrews** [wheaton5/souporcell#158]
I'm running souporcell on two separate pools that contain 3 unique individuals each, so 6 total individuals, which are all from the same laboratory strain. We know from previous work that while this strain is inbred there is still enough genetic variation for other applications (i.e. paternity testing). 

While running souporcell separately on both sample pools, both came back with 2 identified genotypes instead of the 3 that would be predicted since 3 individuals were included. I can also compare which cells passed my UMI and counts filter to which genotype they are assigned. It appears that quite a few of my cells that pass this filter are assigned as doublets by souporcell, enough that it could account for my third missing genotype. It should be noted there are also quite a few doublets and singlets called that don't pass filtering as well. This was particularly surprising that I got the same results from the two separate sample pools. My understanding is that if they were too inbred it wouldn't be able to call genotypes in the first place. For example, if I run souporcell with only the cells that pass the UMI/counts filter, one sample pool all comes back as singlets assigned to one genotype and the other sample pool comes back as all unassigned singlets.  

Is it possible that the 'missing' genotype is being treated as an intermediate of the two other genotypes and is therefore all being assigned as a doublet?

**Comment by wheaton5** [comment]
Variant calling on scRNAseq is much harder and sparser than on bulk RNA which is harder and sparser than on DNA sequencing. This is probably why it isnt working while paternity testing does work. I suggest finding other strains for this type of experiment.

But to answer your questions, yes those are reasonable hypotheses. Souporcell needs to find sufficiently different cluster centers to better explain the data, but if these are very close to one another many cells may be unassigned or if the 3rd cluster was explaining random false positive variant calls and not a 3rd genotype then those cells might be categorized as doublets. 

Are u using a common variants file? This might help.

**Comment by imillercrews** [comment]
That all makes sense! We were using 2bRAD so it was still pretty sparse compared to typical genomic approaches. 

Unfortunately we don't have a common variants file as this is a non-model system. If this is the case though then that works for my purposes as I mainly wanted to use it as a tool to identify cell types that might not be shared across samples and less about which samples they came from. Plus it is a good proof of principal that it would work with other datasets I have that use potentially inbred individuals and were we are interested in how cell types relate to phenotypic traits. 

Think your method worked pretty well all things considered and thank you for your feedback!
