### ISSUE TITLE
Error running clustering

### ISSUE THREAD

**Issue by mxposed** [wheaton5/souporcell#16]
Hello, I just got this error running clustering. I see you just recently committed the off-by-one error fix. If these are related, is the singularity image updated?

```
Traceback (most recent call last):
  File "/opt/souporcell/souporcell.py", line 89, in <module>
    cell_data[cell-1][index] = float(ref_c)/float(ref_c+alt_c)
IndexError: index 7374 is out of bounds for axis 0 with size 7374
```

**Comment by wheaton5** [comment]
Hi,

These are not related. That off by one error was for a new feature that isn't in the current singularity build.

I think you are running into this bug https://github.com/wheaton5/souporcell/issues/4
Is this very shallowly sequenced? The only way this can happen is if there are some cells which have no data for any of the loci. I am intending to fix this, but I think that if you are running into this problem, your data probably won't cluster well anyway. And right now I am in the process of rewriting the clustering portion in rust and the optimization with E/M which I believe will be vastly faster and allow for more restarts etc. So unless you believe your data should be sufficient (UMI/cell > say 2k) I am going to let this one go and not make the same error in my new implementation.

Let me know.

Best,
Haynes

**Comment by mxposed** [comment]
Thank you for the quick reply!
The sequencing is a bit shallow, but not really: 
```
> summary(FetchData(SC65, "nCount_RNA"))
   nCount_RNA   
 Min.   :  502  
 1st Qu.: 2340  
 Median : 3489  
 Mean   : 7480  
 3rd Qu.:12411  
 Max.   :56190  
> summary(FetchData(SC66, "nCount_RNA"))
   nCount_RNA   
 Min.   :  500  
 1st Qu.: 2742  
 Median : 6584  
 Mean   : 7958  
 3rd Qu.:11541  
 Max.   :55095
```

SC65 is the one sample with error, while SC66 is another same we got sequenced simultaneously, and souporcell ran successfully on it.

I'd be happy to fix this myself (as I would like to actually process this sample), so I'd be glad if you point me in the right direction

**Comment by wheaton5** [comment]
Okay, that is only a bit lower than many standard PBMC runs. You must have just gotten incredibly unlucky. I think the fix should be pretty easy. I'll attempt it tomorrow.

**Comment by wheaton5** [comment]
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1_QNPEdYq6P-_Y6DTmLoE9P0ovY2xR58P' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1_QNPEdYq6P-_Y6DTmLoE9P0ovY2xR58P" -O souporcell.sif && rm -rf /tmp/cookies.txt
```

**Comment by mxposed** [comment]
Thank you very much! I've just scheduled this to run, will report in several hours

**Comment by mxposed** [comment]
It ran successfully without errors and the results make sense. Thank you very much!

However the overall results for 2 samples bring several questions, I'll email them to you shortly.

**Comment by mxposed** [comment]
I believe in this new singularity image you broke samtools call.
This is my retag.err:
```
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
```

**Comment by wheaton5** [comment]
Thanks. I'll get this worked out. I guess I have multiple versions of samtools floating around and don't always test from the singularity container directly as it takes 45min to build.

**Comment by wheaton5** [comment]
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1LWKHs-nKXNH5vVkP8iJAgLquiE9FLMb5' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LWKHs-nKXNH5vVkP8iJAgLquiE9FLMb5" -O souporcell.sif && rm -rf /tmp/cookies.txt
```

**Comment by wheaton5** [comment]
should fix it, at least my test *on the singularity container* is passed that point now
