### ISSUE TITLE
Bug when only 1 cluster in data?

### ISSUE THREAD

**Issue by JulianRein** [wheaton5/souporcell#17]
Hi,
first: thanks for the singularity-image, a great way to provide scientific tools!

Now to the issue:
We tried the 99-1 ratio mix of two donors (B and C) from 10X / Zhang et al 2017 ("Massively parallel digital transcriptional profiling of single cells") with Souporcell.
Unfortunately, we got the following error:

```
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory 10X2017data/rundir_99-1
running souporcell clustering
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 446, in <module>
    souporcell(args, ref_mtx, alt_mtx)
  File "/opt/souporcell/souporcell_pipeline.py", line 387, in souporcell
    "-t", str(args.threads), "-l", args.max_loci, "--min_alt", args.min_alt, "--min_ref", args.min_ref,'--out',cluster_file],stdout=log,stderr=log)                              
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['souporcell.py', '-a', '10X2017data/rundir_99-1/alt.mtx', '-r', '10X2017data/rundir_99-1/ref.mtx', '-b', '10X2017data/99-1/outs/filtered_feature_bc_matrix/barcodes.tsv', '-k', '2', '--restarts', '15', '-t', '8', '-l', '2048', '--min_alt', '4', '--min_ref', '4', '--out', '10X2017data/rundir_99-1/clusters_tmp.tsv']' returned non-zero exit status 1.
```

The 50-50 and 90-10 mixes from the same paper run smoothly.
As a side note, when we tried "-k 1" on our data (to get the loss value with only one assumed donor), we also got an error (I did not write it down). 
Is there maybe some issue if the data or the parameters show souporcell only 1 cluster?

Best
Julian

**Comment by wheaton5** [comment]
Thanks. I have not thought about the one cluster case. I will look into that.

For the error, could you post what it says in the souporcell.log file in the output directory?

**Comment by JulianRein** [comment]
Hey, sorry for the late reply, here is the output for the 2017-10X-99:1 data:

`/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
loci being used based on min_alt, min_ref, and max_loci 19076
Traceback (most recent call last):
  File "/opt/souporcell/souporcell.py", line 89, in <module>
    cell_data[cell-1][index] = float(ref_c)/float(ref_c+alt_c)
IndexError: index 8448 is out of bounds for axis 0 with size 8448`

For the case with "-k 1" for our own data, it seems different:
Sourporcell.log ends like "usual"/with k=2, just with only 1 output-dim:

`epoch 110 235635.35473337522
epoch 120 235634.67220186393
repeat 14
epoch 0 449597.12127496727
epoch 10 261566.50874990158
epoch 20 245071.25087495073
epoch 30 239596.40476635238
epoch 40 236845.00997523247
epoch 50 236161.28534847582
epoch 60 235808.97853019924
epoch 70 235698.94204988983
epoch 80 235657.2162644119
epoch 90 235642.5975740829
epoch 100 235637.32052936163
epoch 110 235635.33933947876
epoch 120 235634.66395643842
(235634.6555886272, array([[-107.52100374],
       [ -49.42965239],
       [-102.74596353],
       ...,
       [-135.72020579],
       [-111.02542573],
       [-112.60568309]]))
[0 0 0 ... 0 0 0]
0       0.0
`
However, the 3 files usually created after  "troublet.done" (namely ambient_rna.txt, cluster_genotypes.vcf, consensus.done") are missing, I guess it crashed there.
So seems to not be the same problem.

**Comment by wheaton5** [comment]
The problem from the first file is a bug I already fixed but have not put in the release version yet.
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1LWKHs-nKXNH5vVkP8iJAgLquiE9FLMb5' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LWKHs-nKXNH5vVkP8iJAgLquiE9FLMb5" -O souporcell.sif && rm -rf /tmp/cookies.txt
```
