### ISSUE TITLE
Mixture model Clustering (theory)

### ISSUE THREAD

**Issue by ChantKatrjian** [wheaton5/souporcell#176]
Great script, I have been studying and implementing this design but had a few questions to clear up. 

1. Is the model that is fit to the clustering matrix X (rows_Cells, Columns_variants, Elements _read num supporting each allele of var.) operating at dimensions = number of loci (varients) that meet the requirements? that is to say, each cluster center will represent allele fractions of only one locus (fixed on one column and going through the rows on the matrix)? Or is it operating in some latent space, or is it two dimensional and I have this all wrong?
2. When looking at the ref.mtx and alt.mtx (output from VarTrix convergence scoring), what does the header row represent? column 1 is UMI, column 2 is Barcode, column 3 is read numbers?
3. If the clustering model works on dim = # vartiants, what dimensionality reduction algorithm do you use to bring them down to 2 dimensions?

Apologies in advance if these questions are redundant or simplistic.
Any aid from the community is appreciated.

**Comment by ChantKatrjian** [comment]
So is it accurate to say that the clustering happens in X dimensions, where x is the number of loci that meet the requirements? So on each dimension (assume k = 2), there will be two clusters that represent only 1 variant, where each of those cluster centers will have a different alternate allele fraction based on subsets of cells that have high alternate allele fraction (supporting alt allele) compared to lower alternate allele fraction (supporting ref) for that variant.
 
I understand 2. and 3. thank you.

**Comment by wheaton5** [comment]
Yes. The only wrinkle is that while the clusters are loci dimensional, each cell may interact with those centers on a subset of loci for which they have data. They technically could interact on all dimensions, but it is unnecessary as binom_pdf(0 successes out of 0 trials) = 1 so multiplying a bunch of ones together is unnecessary

**Comment by ChantKatrjian** [comment]
I understand, thank you for the explanation. 
I will mark the issue as closed.
