### ISSUE TITLE
CellBender + Souporcell

### ISSUE THREAD

**Issue by achamess** [wheaton5/souporcell#18]
I'm wanting to use the new CellBender tool that removes ambient RNA computationally from droplets.
https://github.com/broadinstitute/CellBender
 It takes the raw (unfiltered) 10x hd5 file and gives out its own filtered dataset. I took this into souporcell and used the filtered cell barcode list from CellBender.

I am getting a surprisingly high number of doublets called, like ~40-50%. I suspect something is wrong. These are human nuclei data. About ~10k/reads per nucleus.

Any thoughts?

**Comment by achamess** [comment]
I answered my own question and ran souporcell on filtered 10x outs. Largely same results. So not related to CellBender. That leaves me though wondering why so many doublets. And the ambient RNA is results says "ambient RNA estimated as 60.86274482153185%". Something doesn't seem right. Based on the Cellranger metrics, these data look great. Sharp knee plot, 90% fraction reads in cells.

**Comment by wheaton5** [comment]
This will probably be because the clustering just didn't work well. If the clustering went wrong, then may cells may look like doublets and it may appear as if there is tons of ambient RNA as both of these processes rely on a solid clustering. You say 10k reads per nucleus, but how many UMI? Usually single nuclei experiments have more like 400 UMI. I would try using the 1k genomes common variants file to reduce false positive variants (--common_variants option).

**Comment by achamess** [comment]
Thanks Haynes. I think you're right. UMIs are actually quite high with Chromium v3. Even with my shallow seq, I've got ~2800 UMIs/nuc. I reran with the common variants option and also 30 restarts,  and now ambient RNA is 2.5% and doublets are 10%. So an improvement for sure. I guess the question is, what are the right parameters? Could one just keep tweaking these to get the desired outcome? What is a systematic way to adjust and how do you know when to stop? What is the ground truth?

**Comment by wheaton5** [comment]
Great. Good to know Chromium v3 is getting higher umis. Out of curiosity how many donors in this sample? Local optima grow with the number of donors, but I have been working on this and have a pretty good solution. Soon I will be releasing a new version of souporcell. It is completely rewritten and now does expectation maximization with deterministic annealing which allows it to get to the global optimum far more often than the previous gradient descent version and it is also much faster.

**Comment by achamess** [comment]
Thanks! 4 donors. I’ll look out for new version of souporcell. Any estimate on ETA?
Also, to the original question, if I want to use Cellbender (or other ambient RNA tools), I should do that upstream of souporcell?

**Comment by wheaton5** [comment]
I think only an empirical test can be done here. 

So cellblender and other non-genotype tools can know probabilistically how many UMIs to remove from a given cell/gene but not which reads. In that case that all of the reads for a given gene from a given cell come from ambient RNA, then removing them all is valuable to clustering. But in the case that it is a minority of the reads, you may remove the wrong reads and actually make the representation of ambient RNA derived SNPs worse as a percentage. Does this make sense?

**Comment by achamess** [comment]
I get it. Well, I could run souporcell upstream on the raw matrix. Downside would be computation time since it has to process so many  empty/ambient droplets? And then after CellBender, I'd have to modify the clusters.tsv to remove the droplets that CellBender removes. Would be a little more work, but not bad. I'll try both.

**Comment by wheaton5** [comment]
Well does cellblender create a new bam? I was unaware of cellblender until you pointed it out. I would imagine it just removes the counts from the matrices. If that is the case then for souporcell purposes it is just calling the cell barcodes. I always imagined souporcell being run on the cellranger output, but I'm guessing you aren't running cellranger or that you don't trust its cell calling? In any case are cells with less than say 200 UMIs really that useful for anything? you could remove those and run souporcell. But souporcell doublet calling and ambient RNA calling is making an assumption that it is dealing with cell droplets that may be perturbed by doublets and ambient RNA. It doesn't marginalize over the option of the cell being only ambient RNA.

**Comment by achamess** [comment]
No new bam. Just generates a barcode list after filtering. The argument for its use is that it's superior to CellRanger and other tools for calling cells but also subtracting the ambient RNA from the real cells so that you get better definition of cell clusters without spurious gene expression. With nuclei and difficult tissues, there is quite a bit of ambient RNA and spurious expression (example. microglial markers in a neuron cluster).

**Comment by wheaton5** [comment]
Okay. Then it shouldn't affect souporcell so that is fine. souporcell is quite resilient to ambient RNA assuming there is enough data.

**Comment by wheaton5** [comment]
Okay I'm gonna close this but feel free to reopen. ETA on new version is end of the week. I just need to implement and test the known_genotypes option.

**Comment by arutik** [comment]
Hi, 

Sorry I'm not sure if this is directly related, but if I have a fairly similar situation, I am using CellBender on the raw feature barcode matrix for nuclei to correct for ambient RNA with CellBender. And when I previously used souporcell, I ran it on the filtered feature barcode matrix from cellranger, and now I'm seeing that a lot of cells (from CellBender output) are just not in the souporcell results tables. Is it due to souporcell internal filtering or I should just run souporcell on raw feature barcode matrix from cellranger?

Thanks a lot.

Sincerely,
Anna Arutyunyan

**Comment by wheaton5** [comment]
Souporcell does not take a barcode matrix, but it does take the barcodes.tsv file. If you want it to run on more barcodes, use a barcodes.tsv file with them in it. I assume Cellblender outputs something like this? I would not recommend running souporcell with the full barcode set. It was not designed to do so and I'm virtually certain that you will run into problems. 

Hopefully this answers your question. Let me know if it does not.

**Comment by arutik** [comment]
Thanks a lot for your rapid response. 
Yes, CelllBender indeed outputs the barcodes. Just as an idea, what if I take the barcodes that are thought to be cells by CelllBender and run souporcell on them? The list shouldn't be as big as the completely raw barcodes list. 

Sincerely, 
Anna Arutyunyan

**Comment by wheaton5** [comment]
> what if I take the barcodes that are thought to be cells by CelllBender and run souporcell on them?

this is exactly what i recommend

**Comment by arutik** [comment]
Ah ok got it. And if I pass the CellBender barcodes to souporcell, is souporcell going to look for any .h5 files or does it need any specific directory structure (like with cellranger output)? Or just the barcodes and the cellranger output possorted.bam? 

Thank you.

**Comment by wheaton5** [comment]
It doesn't depend on any directory structure that it doesn't create itself. The singularity image, however, does require that all files are downstream from where you are running it, because it only mounts directories downstream so it wouldn't be able to see anything, like, ../barcodes.tsv

Souporcell does not use the h5 file. Every file it uses are in the arguments you pass it.

**Comment by arutik** [comment]
Huge thank you!!!

Sincerely,
Anna Arutyunyan

**Comment by arutik** [comment]
Hi, can I ask if souporcell does any kind of internal filtering of cells?
I ended up running it on barcodes out of CellBender with the possorted_genome bam file (out of cellranger), and in the souporcell results I am still missing quite a few cells. Maybe the possorted bam out of cellranger only contains the filtered cellranger barcodes?

Thank you.

Sincerely,
Anna Arutyunyan

**Comment by wheaton5** [comment]
I’m fairly confident that whether there is any data for a cell or not, if it is in your barcodes file it will be in the output clusters file as your barcodes file. Can you double check that you gave the right file? Also if you had a previous run and you reran, it will not overwrite old results. I have set it up to try to use partial results when possible. Maybe that is the problem?

**Comment by arutik** [comment]
Sorry indeed it was just a flaw in my scripts, now I found all the missing cells.

Thank you!
