### ISSUE TITLE
Decreasing doublet rate?

### ISSUE THREAD

**Issue by ktpolanski** [wheaton5/souporcell#184]
Hello, I've got a bit of a problem sample on my hands. I'm running souporcell like so, in the standard fashion:

```bash
singularity exec -B $PWD souporcell/souporcell.sif souporcell_pipeline.py -i $SAMPLE.bam -b $SAMPLE.tsv -f ~/cellranger/GRCh38-2020-A/fasta/genome.fa -t 23 -o $SAMPLE -k 2 --skip_remap True --common_variants souporcell/common_variants_grch38-2020-A.vcf
```

However, the result has half the cells deemed doublets. This persists when I merge the sample with two others that were part of the same multiplexing scenario.

Is there anything I can do to try to improve the calling rate? Thanks a lot and sorry for the trouble - never ran into this before.

**Comment by wheaton5** [comment]
My instinct is that there must be a data quality problem. Obviously also software problem, but there is some level of signal to noise that we need in order for the doublet detection to act well. You can try doublet detection with other tools (not using genotypes) to see what they say.

**Comment by ktpolanski** [comment]
Yeah, it might be a data problem. I'm inferring there's nothing I can try to alter parameter side in that case. No worries!
