### ISSUE TITLE
Using bulk RNA-seq to match identity with souporcell

### ISSUE THREAD

**Issue by suhuanhou** [wheaton5/souporcell#185]
Hi. Souporcell worked nicely to cluster my snRNA-seq data into different donors. But now I need to go back and match the donor with the souporcell call. I've done regular bulk RNA-seq on each individual donor. Is there a good way now to use that bulk RNA-seq data to see which donor corresponds to each cluster?

**Comment by wheaton5** [comment]
I have a script shared_samples.py for this in the repository.

**Comment by suhuanhou** [comment]
That's really great! Thank you for your reply!
