### ISSUE TITLE
error in freebayes : unrecognized option '--max-coverage'

### ISSUE THREAD

**Issue by suhuanhou** [wheaton5/souporcell#187]
freebayes -f /share/home/shh/download/refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa -iXu -C 2 -q 20 -n 3 -E 1 -m 30 --min-coverage 6 --max-coverage 100000 ${souporcell_out}minitagged_sorted.bam

freebayes: unrecognized option '--max-coverage'
did you mean --min-coverage ?

**It seems that freebayes does not have this option, why does it appear in the souporcell manual?**

**I tried to remove the '-- max coverage' parameter, but it returned with 'Aborted (core dumped)'. How can I solve this problem? Thank you for your reply!**

**Comment by wheaton5** [comment]
for the version of freebayes in the singularity build it does have that option. i guess it was removed since then. I am in the process of making a new singularity build and updating the software versions

**Comment by wheaton5** [comment]
new singularity build made. Hopefully this will fix your problems.
