### ISSUE TITLE
singularity issue

### ISSUE THREAD

**Issue by bjstewart1** [wheaton5/souporcell#2]
I have a quick query about getting this to work with singularity, as it is throwing an error.

Singularity version is okay.
`singularity --version`
> singularity version 3.1.1

Does not throw an error with lolcow.sif test... 

Then attempting to run the test (NB `wget https://sra-download.ncbi.nlm.nih.gov/traces/sra47/SRZ/005398/SRR5398235/A.merged.bam
` is broken...
But - `wget https://sra-pub-src-1.s3.amazonaws.com/SRR5398235/A.merged.bam.1` does work.. )
I get this error:
`singularity exec souporcell.sif souporcell_pipeline.py -i A.merged.bam.1 -b GSM2560245_barcodes.tsv -f GRCh38_full_analysis_set_plus_decoy_hla.fa -t 8 -o soup_or_cell_test -k 4`

> FATAL:   container creation failed: mount /proc/self/fd/3->/software/singularity-3.1.1/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/3: failed to mount squashfs filesystem: invalid argument

Exactly the same error with my own data.

Any ideas?

**Comment by wheaton5** [comment]
First of all thank you for pointing out the dead link. Was good last week... Maybe I should host that myself just to make sure it doesn't happen again. For now it is changed in the docs.

Sometimes the wget from google drive fails. How big is the souporcell.sif file? It should be 1.2gb and the md5sum is 0bee1ede88d23e61a2c9bc33129ab380. If that is all right, can you try singularity exec souporcell.sif echo hello

Right now I cannot reproduce this, but from some googling I found
rm -rf .singularity/
as a potential solution. Here is where I found it https://github.com/sylabs/singularity/issues/2625
Hope this works!

**Comment by bjstewart1** [comment]
The problem was wget from google drive. The file was <1.3gb.
It works now I have deleted and repeated the download.
This is true:
>  Google drive makes it annoyingly difficult to download via the terminal.

Thanks for the prompt help.
