### ISSUE TITLE
Reach memory limit (96G) for low number of cell

### ISSUE THREAD

**Issue by silvainp** [wheaton5/souporcell#20]
------------------------------------------------------------
# LSBATCH: User input
./souporAg.sh
------------------------------------------------------------
TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 143.

**Comment by wheaton5** [comment]
Dealt with over slack. The issue was with region chunking I had a bug if a single chromosome was a large % of the genome. fixed now.
