### ISSUE TITLE
barcodes, cell counts in clusters.tsv

### ISSUE THREAD

**Issue by aranham** [wheaton5/souporcell#207]
Hi, 

I have a pooled sample that has ~650000 barcodes in the raw matrix and 15000 barcodes (cells) in the filtered matrix. I run souporcell giving the raw matrix as input and run it with remap and without providing a reference genotype file. At the end of the run my clusters.tsv file has 53000 barcodes detected as singlets or doublets which is quite a bit higher than the number of cells in the filtered matrix from cellranger (15000). How does souporcell decide if a barcode is background/ambient contamination or an actual cell as it filters from 650000 to 53000?

Thanks!

Best,
Michelle

**Comment by wheaton5** [comment]
Souporcell expects the filtered barcode file and does not even tries to
tell cell from non cell barcodes. Rerun with the filtered barcode file.

Best,
Haynes

**Comment by wheaton5** [comment]
Edit: try not tries
