### ISSUE TITLE
Can I use one vcf to identify two clusters?

### ISSUE THREAD

**Issue by xxl619755841** [wheaton5/souporcell#208]
Hello:
Thanks for your great tool !
I have a simple question. In my experiment, I have a sample mixed maternal cells and fetal cells. But for some reason, I can only get WGS data from mom. So can I use souporcell to identify maternal cells, and regard other singlets as fetal cells ?
I found that value of k must be equal to the number of known_genotypes_sample_names, and if I use k=1, the result will only have one cluster. 
How can I achieve the purpose above?

Thanks for your patience!

**Comment by wheaton5** [comment]
You will need to not use known genotypes and only determine which cluster is maternal after clustering.

**Comment by xxl619755841** [comment]
So can I determine the maternal cluster by comparing the WGS vcf and genetype vcf output from souporcell？I had tried to distinguish them on transcriptome and cell type but failed.

**Comment by wheaton5** [comment]
How was the sample taken? If taken from the placenta, the majority cluster is fetal. If taken from the decidua, the majority cluster is maternal. If taken some other way, I'm not sure. But doing it via cell type should also work. Use common cell type clustering systems, then use scmap to label cell types, then use biological knowledge to determine which cell types are expected from fetal and maternal sources.

**Comment by xxl619755841** [comment]
Thanks for your answer! I'll give it a try like you said!
