### ISSUE TITLE
singularity - vcf merging problem

### ISSUE THREAD

**Issue by kerimsecener** [wheaton5/souporcell#21]
Hello Haynes,

I am having a hard time running the pipeline in singularity: (version singularity version 3.1.0):

/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/asecene/anaconda3/envs/freebayes/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/asecene/souporcell/souporcell_pipeline.py", line 461, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/home/asecene/souporcell/souporcell_pipeline.py", line 362, in freebayes
    subprocess.check_call(["bcftools", "concat"] + all_vcfs, stdout = vcfout)
  File "/home/asecene/anaconda3/envs/freebayes/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bcftools', 'concat', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_0_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_1_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_2_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_3_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_4_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_5_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_6_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_7_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_8_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_0.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_2_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_5_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_6_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_3_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_1_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_4_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_5_2.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_2.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_3.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_7_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_4.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_2_2.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_9_5.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_8_1.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_3_2.vcf', '/fast/CF_Sequencing/work_dir/cfische/SP014/CR3_3/SOZE1-Villi/sozevilli/outs/soup_output/soup_output_singul/souporcell_3_3.vcf']' returned non-zero exit status 1.

Somehow bcftools' having a hard time merging the vcf files ?

Thanks,
Kerim

**Comment by wheaton5** [comment]
Hi Kerim,

Thanks for your interest in souporcell. I think there should be a bcftools.err file in the output directory? I am also uncertain as to whether the singula/rity container is being used or not. 
I see /home/asecene/souporcell/souporcell_pipeline.py in your output. 
If I do the following command
singularity exec souporcell.sif which souporcell_pipeline.py
I get the following output
/opt/souporcell/souporcell_pipeline.py

/opt is the singularity specific directory in which all of the software in the container is installed. It looks to me like you might have also cloned the repo and are potentially accidentally running it directly instead of through singularity. Sorry if this is not the case. I just want to get to the bottom of the problem. Can you share with me your command to run souporcell as well as any bcftools.err contents from your output directory.

Best,
Haynes

**Comment by kerimsecener** [comment]
Thanks for the reply. I was indeed stupidly running it outside of the singularity.
It worked now !

Best,

Kerim
