### ISSUE TITLE
Error occured in clustering step

### ISSUE THREAD

**Issue by ilovegreentea** [wheaton5/souporcell#213]
Error occured in clustering step

I successfully generated a cluster.tsv file without the genotyping data. 
However, when I include genotyping data, an error occurs, and the cluster.tsv file is not generated. 
The error message in the cluster.err file indicates a panic in the Rust code at line 330

please give me any comments to run this....

### cluster.err 
total loci used 2186
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:330:50

### Running pipeline
root@DESKTOP-N6DV9KB:/home/hkt/mRCC_IO_T_M1# sudo singularity exec --bind /home/hkt/mRCC_IO_T_M1/ /home/hkt/singularity-ce-3.11.4/souporcell_latest.sif souporcell_pipeline.py -i possorted_genome_bam.bam -b barcodes.tsv -f hg38.fa -t 20 -o /root/mRCC_IO/ -k 3 --known_genotypes mRCC_IO_T_reheader_new.vcf --known_genotypes_sample_names mRCC_IO_002_T mRCC_IO_016_T  mRCC_IO_017_T
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory /root/mRCC_IO/
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 3 -a /root/mRCC_IO//alt.mtx -r /root/mRCC_IO//ref.mtx --restarts 100 -b barcodes.tsv --min_ref 10 --min_alt 10 --threads 20 --known_genotypes /root/mRCC_IO//common_variants_covered.vcf --known_genotypes_sample_names mRCC_IO_002_T mRCC_IO_016_T mRCC_IO_017_T
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 593, in <module>
    souporcell(args, ref_mtx, alt_mtx, final_vcf)
  File "/opt/souporcell/souporcell_pipeline.py", line 531, in souporcell
    subprocess.check_call(cmd, stdout = log, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/souporcell/target/release/souporcell', '-k', '3', '-a', '/root/mRCC_IO//alt.mtx', '-r', '/root/mRCC_IO//ref.mtx', '--restarts', '100', '-b', 'barcodes.tsv', '--min_ref', '10', '--min_alt', '10', '--threads', '20', '--known_genotypes', '/root/mRCC_IO//common_variants_covered.vcf', '--known_genotypes_sample_names', 'mRCC_IO_002_T', 'mRCC_IO_016_T', 'mRCC_IO_017_T']' returned non-zero exit status 101.

**Comment by apredeus** [comment]
Hi, did you ever figure out what is causing this? Thank you!

**Comment by ilovegreentea** [comment]
No, I used demuxlet(with genotype) and sourpocell(without genotype) both.

**Comment by apredeus** [comment]
Thank you for letting me know, much appreciated.
