### ISSUE TITLE
Would using a filtered VCF based on T and E values result in more accurate results?

### ISSUE THREAD

**Issue by G3N0M3** [wheaton5/souporcell#214]
Hi! Thanks for your work.
I was doing some experiments with your tool and came to a question that I had to ask.

As posted in this [post](https://github.com/wheaton5/souporcell/issues/110), there is a T and E value each for each variant, each meaning that a variant is a true positive or a variant is from a ambient RNA.
Based on the T and E, I've selected variants that have a posterior over a certain value from the freebayes output vcf file.
I then used the pipeline starting from vartrix.

Naively, I thought this was a good idea: more concrete variants, more accurate results.
I am just looking at the results, and wanted to know how you think the use of filtered SNPs would affect the results.

**Comment by wheaton5** [comment]
I have not tested this but I think it would in general be good. However, the ambient rna detection is the least robust part of the process and depends on the accuracy of everything before it. So depending on your sample it may be good or not.

**Comment by G3N0M3** [comment]
@wheaton5 Thanks for your opinion!
