### ISSUE TITLE
Running souporcell across multiple samples

### ISSUE THREAD

**Issue by samfenske** [wheaton5/souporcell#232]
Hello, thank you for having such a wel-documented package. I have a quick question that I would like clarity on. I'm running souporcell on different libraries such that I independently ran souporcell 18 times for the 18 libraries. Each library contains cells pooled together from 5 donors, and each library contains cells from the same five different donors (each library is a different perturbation). 

My question is, are the clusters assigned consistent across each library? More specifically, if a cell from one library is assigned to cluster 4 can I assume that a cell assigned to cluster 4 in a different library is the same genotype? I'm not sure how souporcell assigns the cluster names- it doesn't seem to be highest count is the highest number cluster so it seemed reasonable to think that across souporcell runs I could just rely on the cluster number to represent the 5 donors.

Thank you!

**Comment by wheaton5** [comment]
No, cluster names are arbitrary. 

There is a shared_samples.py script which attempts to match clusters, tho its been a bit iffy at times. I should revisit this.

**Comment by samfenske** [comment]
Thank you for the quick response. Yes I went through the issues and found this- will investigate.
