### ISSUE TITLE
Hosting Singularity image on Sylabs?

### ISSUE THREAD

**Issue by Sxmple-DavidSchmidt** [wheaton5/souporcell#238]
I was wondering why you chose to host the Singularity image in such an unconventional manner. Why didn't you opt for a more accessible platform like [sylabs](cloud.sylabs.io)? I am running into problems when trying to use Nextflow to make use of the container.

**Comment by wheaton5** [comment]
I can do that. Ill post here again when its done

**Comment by wheaton5** [comment]
This is done now. And updated release to 
singularity pull --arch amd64 library://wheaton5/souporcell/souporcell:release
