### ISSUE TITLE
Easiest way to identify which sample is which individual

### ISSUE THREAD

**Issue by achamess** [wheaton5/souporcell#24]
This is more an experimental question rather than a software one. Souporcell has done a nice job of clustering the different individuals in my pools, but now I want to go back and match a sample with a cluster. If I were to redo the experiment, I would have used the strategy recommended in the latest edition of the preprint, but that's not an option now.

What is the easiest and cheapest way to match the clusters with a sample. PCR based genotyping? What's a good way to identify variants from the clusters that would allow me to identify the sample unambiguously?

**Comment by wheaton5** [comment]
I don't have something for this right now. But I have ideas on how it could work. I think I would first look at the highly expressed loci  where a genotype can be called confidently for each cluster. Then I would assign 0 for homozygous major allele fraction and 1 for het or homozygous minor allele. Then I would look for variants with a high amount of diversity (where those previous vectors are sum close to 1/n). Then I would split the clusters into the two groups accordingly based on that highly informative SNP and I would recurse on each subgroup in the same fashion until every subgroup size is 1. That is a greedy method, but that would be my first try.

**Comment by wheaton5** [comment]
correction, that vector should average close to 0.5, not sum to 1/n

**Comment by achamess** [comment]
Thanks!
It might be a nice feature to add to the software to have a script that basically does this and provides a set of maximally efficient genes to genotype with targeted genotyping, in line with the approach you outlined.

**Comment by achamess** [comment]
I tried using the script. It took more than 24 hours, so I stopped it, thinking something was wrong. should it take that long? Are you able to make a new singularity build with the updated code?
