### ISSUE TITLE
Rename of Singularity to Apptainer causes confusion

### ISSUE THREAD

**Issue by paulmenzel** [wheaton5/souporcell#242]
https://github.com/wheaton5/souporcell/blob/806da4f0190b0e89a33473e7da91af868b948427/README.md?plain=1#L28-L32

Singularity was renamed to [Apptainer](https://apptainer.org/) and for whatever reason reset the version number but still provide a symbolic link `singularity`.

1.  [Announcing Apptainer release 1.0.0](https://apptainer.org/news/apptainer-1-0-0-20220303/) from March 2022
2.  [Singularity Compatibility](https://apptainer.org/docs/user/main/singularity_compatibility.html#singularity-compatibility)
3.  [Apptainer 1.0.0 seems based on Singularity 3.8.x](https://github.com/apptainer/apptainer/releases/tag/v1.0.0):

    > Other changed defaults / behaviours since Singularity 3.8.x

It’d be great if the README could be updated.

PS: Currently in our environment:

    $ singularity --version
    apptainer version 1.2.4

**Comment by wheaton5** [comment]
This is why heng li says dont have any dependencies lol

**Comment by wheaton5** [comment]
if you write everything from scratch, nothing can change unless you change it

**Comment by wheaton5** [comment]
so will syslabs change their name in like 5 days to appslabs or something? Give me a few days and I'll update.

**Comment by athuyvo** [comment]
I'm experiencing the same issue and wonder if this has been changed, yet?

**Comment by wheaton5** [comment]
i would not characterize this as an "issue". I'll update the docs, but nothing is broken.

**Comment by wheaton5** [comment]
Now it reads
requires singularity >= 3.0 or apptainer version >= 1.0.0 (singularity rebranded as apptainer and changed its version numbers)

is that sufficient?

**Comment by wheaton5** [comment]
I think this is done, reopen if needed.

**Comment by paulmenzel** [comment]
Thank you. Addressed by commit https://github.com/wheaton5/souporcell/commit/20812878880589ef99df58bff39fed02be38e835.

PS: If you didn’t know yet: Adding

> Closes: https://github.com/wheaton5/souporcell/issues/242

to the commit message, would cause GitHub to close the issue automatically, once it’s committed.
