### ISSUE TITLE
error when running consensus.py

### ISSUE THREAD

**Issue by royoelen** [wheaton5/souporcell#28]
I'm trying to run the 'consensus' step in your pipeline (I'm running each step manually), and am incountering an issue.

I'm running the command:

`
python /exppath/souporcell_v2/software/souporcell/consensus.py -a /exppath/souporcell_v2/count_alleles/matrices/180920_lane1_wes_unremapped_alt.mtx -r /exppath/souporcell_v2/count_alleles/matrices/180920_lane1_wes_unremapped_ref.mtx -c /exppath/souporcell_v2/soupor_cluster/clusters/180920_lane1_wes_unremapped_cluster.tsv -v /exppath/demux_relevant_samples/WES_per_lane_mmaf002/180920_lane1_wes.vcf_mmaf002.vcf --soup_out /exppath/souporcell_v2/soupor_consensus/consensci/180920_lane1_wes_unremapped.soup --vcf_out /exppath/souporcell_v2/soupor_consensus/consensci/180920_lane1_wes_unremapped.vcf
`

and getting the issue:

`
28789 excluded for potential RNA editing
WARNING:pystan:No module named 'stanfit4anon_model_c58d6755a445ee1723e096eb7e36ea75_355834653533342947'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
0 doublets excluded from genotype and ambient RNA estimation
Traceback (most recent call last):
  File "/exppath/souporcell_v2/software/souporcell/consensus.py", line 196, in <module>
    cluster = int(tokens[2])
ValueError: invalid literal for int() with base 10: '-464.86'
`

I did the clustering with the newer Rust based 'souporcell' step instead of the Python tensorflow one.

Is there a specific version of a library or Python I should use, or is there something wrong in my approach?

**Comment by wheaton5** [comment]
I have a conda environment saved. After unzipping, you should be able to do
conda env create -f souporcell_env.yml
conda activate souporcell
[souporcell_env.yaml.zip](https://github.com/wheaton5/souporcell/files/3939381/souporcell_env.yaml.zip)

**Comment by wheaton5** [comment]
Also you can run the steps individually but through the singularity container.

**Comment by royoelen** [comment]
> I have a conda environment saved. After unzipping, you should be able to do
conda env create -f souporcell_env.yml
conda activate souporcell
souporcell_env.yaml.zip

I tried this, and this solved the stan/pickling part of the error, but not the other part:

`28789 excluded for potential RNA editing
0 doublets excluded from genotype and ambient RNA estimation
Traceback (most recent call last):
  File "/exppath/souporcell_v2/software/souporcell/consensus.py", line 196, in <module>
    cluster = int(tokens[2])
ValueError: invalid literal for int() with base 10: '-464.86'`

I did have to change the ipython specification to just the version number, otherwise I get a ResolvePackageNotFoundError with Conda

> Also you can run the steps individually but through the singularity container.

I cannot run Singularity on our cluster unfortunately

**Comment by wheaton5** [comment]
I suspect you are giving the consensus.py the output of souporcell clustering and not the output of troublet? In the former, that column will correspond to a log likelihood. In the latter it should refer to a cluster number. Is this the problem?

**Comment by royoelen** [comment]
If I supply it with the '-d' or '--doublets' parameter, I get:

`usage: consensus.py [-h] -c CLUSTERS -a ALT_MATRIX -r REF_MATRIX [-p PLOIDY]
                    --soup_out SOUP_OUT --vcf_out VCF_OUT -v VCF
consensus.py: error: unrecognized arguments: --doublets /exppath/souporcell_v2/soupor_doublet/doublet_output/180920_lane1_wes_unremapped_doublets.tsv
`

I understand that in the cluster files, the second column is the cluster and the third is a likelyhood. If I change your code on line 196 of consensus.py:
`cluster = int(tokens[2])` to `cluster = int(tokens[1])`

it continues on, but I have to add an elif to check if all cells are there after:
`for (cell, loci_counts) in cell_counts.items():
    if cell-1 in doublets:
        continue`

or it will crash because it can't find that cell. I'm not entirely sure on how your code works, so maybe what I am trying does not make sense.

**Comment by wheaton5** [comment]
Sorry, that option should have been removed. It used to be the case that there would be a cluster output from souporcell.py and a doublet output from troublet and consensus.py would take both of them. Now, troublet outputs a full clusters file with slightly different format. You need to run troublet on the souporcell output and then the output of troublet should be run through consensus.py. I need to update the documentation on running things step by step. Another option you have is that you can run souporcell_pipeline.py without singularity which deals with all of this stuff.

**Comment by royoelen** [comment]
> Sorry, that option should have been removed. It used to be the case that there would be a cluster output from souporcell.py and a doublet output from troublet and consensus.py would take both of them. Now, troublet outputs a full clusters file with slightly different format. You need to run troublet on the souporcell output and then the output of troublet should be run through consensus.py. I need to update the documentation on running things step by step. Another option you have is that you can run souporcell_pipeline.py without singularity which deals with all of this stuff.

Ah, I see. Putting the troublet output instead of the souporcell output after the -c parameter works. Great, thanks!

**Comment by wheaton5** [comment]
I'll keep this open until I get my shit together and update the documentation and options. Thanks for bringing this to my attention.

**Comment by wheaton5** [comment]
docs updated, closing
