### ISSUE TITLE
ulimit / other issues

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [wheaton5/souporcell#3]
Thanks for making this great tool!

I'm curious about estimated run times for the pipeline. I ran the following command:

singularity exec ./souporcell.sif souporcell_pipeline.py -i SLNR_L3_possorted_genome_bam.bam -b SLNR_L3_barcodes.tsv -f GRCh38_full_analysis_set_plus_decoy_hla.fa -t 8 -o SLNR_PBMC_L3_souporcell -k 4 --ignore True

I started the workflow 2.5 hrs ago and it is currently at the "generating fastqs with cell barcodes and umis in readname" stage. I'm wondering if the pipeline has stalled out and, if not, what the estimated total run time will be.

Thanks,
Chris

**Comment by wheaton5** [comment]
Hi Chris,

Thanks for your interest. The improvement to variant calling we get does require quite a bit of computation. First we convert bam to fastq while putting the cell barcodes and UMIs in the readname (the stage you are at). I should do some testing, but that stage should be nearly done with that number of cores. It simply uses pysam + some python to do this and it uses the cores you give it. Then it remaps with minimap2 also using the cores indicated. The main stage that cannot use an arbitrary number of cores is the bam sorting stage which comes next. Then comes variant candidate calls using freebayes and then allele counts per cell using vartrix. Freebayes should be the limiter here as it is looking at all positions. After that, we get to clustering, doublet calls, and cluster genotyping/ambient RNA detection. At the moment, clustering may take a tens of minutes or a few hours depending on the settings.

I understand that this runtime is quite longer than other paper have quoted. But those quotes are not for the whole process, but just for the clustering portion. And we have plans on improving the runtime of our clustering. In fact, their variant calling methods often take far longer (12hrs+) because they are working on the much worse alignments of the STAR bam from cellranger. Right now for a human sample I would expect around 8 hours for the whole process with 8 cores, but we hope to improve that.

At this point I would not think that the process is stalled. Please let me know if it is not done tomorrow.

Best,
Haynes

**Comment by chris-mcginnis-ucsf** [comment]
Thanks for the quick response. That runtime is totally reasonable, just was curious! Will get back in touch if it's not finished tomorrow.

Chris

**Comment by chris-mcginnis-ucsf** [comment]
Hi again Haynes,

I just checked on the job after letting it run on Sunday -- got the following output (don't know when it actually threw the error):

checking modules
imports done
checking fasta
creating chunks
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
cleaning up tmp fastqs
repopulating cell barcode and UMI tags
cleaning up tmp samfiles
sorting retagged bam files
merging sorted bams
8
8
running freebayes
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 266, in <module>
    "-q","20","-n", "3", "-E","1","-m","30","--min-coverage","6","--pooled-continuous",final_bam],stdout=filehandle)

  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 1254, in _execute_child
    errpipe_read, errpipe_write = os.pipe()

OSError: [Errno 24] Too many open files


I'm trying to run it again after resetting my open files limit to 2048 (originally was at 1024). Hoping this will fix the issue -- if it doesn't, what would your advice be?

Chris

**Comment by wheaton5** [comment]
Hi Chris,

Sorry for the early user woes. This could easily be a problem with my pipeline, but I have not run into this myself. And this could be tricky. Seems like there are a lot of potential things that could cause this.

For my knowledge, what system are you running this on? 1024 seems very low for a linux system. Is this on mac or a vm on a mac? It could also be a singularity fs mount issue...

I just checked my ulimit -a on our farm and on my mac and it says my limits for open files are 131072 and 4864 respectively (not that I have tried to run on my mac). Can u run ulimit -a in the terminal and tell me the output?

Still I don't understand how I am opening so many files. Can you tell me about your reference? #contigs/chroms, length of genome? 

Looking at the code I seem to be closing all of my files in that part of the program, but I do so in bulk after the freebayes step (the step you are at). I could close as they are ready to be closed.

I should implement the ability to restart from a partially completed pipeline. I'll try to get on that tomorrow to improve iteration time on things like this.

Again I apologize for the issues and am dedicated to getting this working for you.

Best,
Haynes

**Comment by chris-mcginnis-ucsf** [comment]
Hey Haynes,

Regarding your previous note, my responses:

(1) I think it is a great idea to be able to restart from a partially completed pipeline! As it stands, my troubleshooting is moving along quite slowly because I have to wait a workday to find the next error... 

(2) I'm using the reference you provide code to download in the tutorial (e.g., using wget http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa)

(3) Here's my ulimit -a output:

![image](https://user-images.githubusercontent.com/40582930/61735124-26aa9c80-ad38-11e9-9680-b0aa2c66d619.png)

When I try to go higher than 2048, I get the following error: ulimit: open files: cannot modify limit: Operation not permitted

I'm a bit of a noob in this area (pretty comfortable with R, bioC, etc., but everything get's a bit hazy outside of this admittedly confined comfort zone...) so I could very likely be messing something obvious up. 


With all of that being said, after upping the file number limit and re-running the pipeline (with upped number of threads and cores and after deleting all of the various outputs from the failed run -- i.e., starting from scratch), I'm now getting a completely new error...

singularity exec ./souporcell.sif souporcell_pipeline.py -i SLNR_L3_possorted_genome_bam.bam -b SLNR_L3_barcodes.tsv -f GRCh38_full_analysis_set_plus_decoy_hla.fa -t 16 -o SLNR_PBMC_L3_souporcell -k 8 --ignore True

checking modules
imports done
checking bam for expected tags
checking fasta
creating chunks
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 147, in <module>
    "-r200","-p.5","-N20","-f1000,5000","-n2","-m20","-s40","-g2000","-2K50m","--secondary=no",args.fasta]+region_fastqs[index], stdout = samfile, stderr = minierr)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['minimap2', '-ax', 'splice', '-t', '16', '-G50k', '-k', '21', '-w', '11', '--sr', '-A2', '-B8', '-O12,32', '-E2,1', '-r200', '-p.5', '-N20', '-f1000,5000', '-n2', '-m20', '-s40', '-g2000', '-2K50m', '--secondary=no', 'GRCh38_full_analysis_set_plus_decoy_hla.fa']' returned non-zero exit status 1.

Any and all advice is more than appreciated!!
Chris

**Comment by wheaton5** [comment]
Hi,

Yes, I will get on dynamic restart from a partially complete pipeline. Shouldn't be too difficult.

There should be a file in the output directory called minimap.err file. Although I see now that I let all threads write to that file at the same time, so I should create one for each thread. That could be the problem. But if you could take a look at that file and post it here or send it to me at whheaton@gmail.com I will hopefully be able to tell more.

Best,
Haynes

**Comment by chris-mcginnis-ucsf** [comment]
File just has this line:

[ERROR] missing input: please specify a query file to map or option -d to keep the index

**Comment by wheaton5** [comment]
Also it looks like the ulimit change you made fixes that issue, but also changing your reference to hg19/GRCh37 or just removing a bunch of the tiny alt/decoy contigs from the GRCh38 reference would help that situation.

**Comment by wheaton5** [comment]
[ERROR] missing input: please specify a query file to map or option -d to keep the index

Ok looks like an easy fix. But I'll need to make the fix and then rebuild the singularity container which takes about 30min. I'll post here when it is up.

**Comment by chris-mcginnis-ucsf** [comment]
Great! Thanks for the effort!!

**Comment by wheaton5** [comment]
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OQy8pLmwiT9YLnnadw3NtiKTjr_f5lYX' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OQy8pLmwiT9YLnnadw3NtiKTjr_f5lYX" -O souporcell.sif && rm -rf /tmp/cookies.txt

I have tested in so far that it can load all of the python packages (the tensorflow and pystan are tricky). But I'd rather it pass a full test before putting this version in the README. I'll do my own testing, but go ahead and get started with this fix. I promise to get dynamic pipeline restart working by next Monday.

Thanks for you interest and patience.

**Comment by chris-mcginnis-ucsf** [comment]
Hmm... just tried this after deleting my old 'souporcell.sif' and got the following error:

FATAL:   image format not recognized

Here was my command:

 singularity exec ./souporcell.sif souporcell_pipeline.py -i SLNR_L3_possorted_genome_bam.bam -b SLNR_L3_barcodes.tsv -f GRCh38_full_analysis_set_plus_decoy_hla.fa -t 16 -o SLNR_PBMC_L3_souporcell -k 8 --ignore True

**Comment by wheaton5** [comment]
double check the download worked. 

ls -lah souporcell.sif

it should be 1.3Gb

**Comment by wheaton5** [comment]
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OQy8pLmwiT9YLnnadw3NtiKTjr_f5lYX' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OQy8pLmwiT9YLnnadw3NtiKTjr_f5lYX" -O souporcell.sif && rm -rf /tmp/cookies.txt
```

ugh, markdown reformated the text. try copying this command instead.

**Comment by chris-mcginnis-ucsf** [comment]
great, it's running now. thanks for YOUR patience! If I can get it running, I'm sure most everyone else will be able to, as well.

Will let you know how it goes.
Chris

**Comment by wheaton5** [comment]
It should also be noted that you can use the container to run things step by step. So the README contains step by step instructions with commands. To do that with the container you just need to run singularity exec souporcell.sif <command>. This isn't tested, but may speed up your process until the dynamic restart is implemented.

**Comment by chris-mcginnis-ucsf** [comment]
ah, good call.

**Comment by chris-mcginnis-ucsf** [comment]
New error at the "repopulating cell barcode and UMI tags" step:

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 163, in <module>
    p = subprocess.Popen(["retag.py","--sam",minimap_tmp_files[index],"--out",outfile])
IndexError: list index out of range

Thoughts?

**Comment by wheaton5** [comment]
Similar issue as before. I'll post here when I have a new container.

**Comment by wheaton5** [comment]
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1vIZnpMSU6ZKmn5xQWjd6otC1zpxSWsSn' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1vIZnpMSU6ZKmn5xQWjd6otC1zpxSWsSn" -O souporcell.sif && rm -rf /tmp/cookies.txt
```

Have a go.

**Comment by chris-mcginnis-ucsf** [comment]
Hello again!

I feel like this thread should be renamed "Haynes helping Chris troubleshoot" but, alas, I've run into a new error that I would appreciate your advice on.

So the pipeline got further than before (hooray!):

checking modules
imports done
checking bam for expected tags
checking fasta
creating chunks
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
cleaning up tmp fastqs
repopulating cell barcode and UMI tags
cleaning up tmp samfiles
sorting retagged bam files
merging sorted bams
16
16
running freebayes
merging vcfs
running vartrix


However, at the 'running vatrix' step, I got the following output:

08:26:16 [ERROR] Warning! Zero variants found in input VCF. Output matrices will be by definition empty but will still be generated.
08:26:16 [ERROR] The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs?
running souporcell clustering
running souporcell doublet detection
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2695:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 306, in <module>
    subprocess.check_call(["troublet","--alts",alt_mtx,"--refs",ref_mtx,"--clusters",cluster_file],stdout=dub)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['troublet', '--alts', 'SLNR_PBMC_L3_souporcell/alt.mtx', '--refs', 'SLNR_PBMC_L3_souporcell/ref.mtx', '--clusters', 'SLNR_PBMC_L3_souporcell/clusters_tmp.tsv']' returned non-zero exit status 101.


And here's the output from minimap.err:

[M::mm_idx_gen::61.274*1.47] collected minimizers
[M::mm_idx_gen::67.081*2.39] sorted minimizers
[M::main::67.082*2.39] loaded/built the index for 3366 target sequence(s)
[M::mm_mapopt_update::67.082*2.39] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 3366
[M::mm_idx_stat::71.107*2.31] distinct minimizers: 382142233 (93.76% are singletons); average occurrences: 1.331; average spacing: 6.325
[M::main] Version: 2.7-r654
[M::main] CMD: minimap2 -ax splice -t 16 -G50k -k 21 -w 11 --sr -A2 -B8 -O12,32 -E2,1 -r200 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g2000 -2K50m --secondary=no GRCh38_full_analysis_set_p$
[M::main] Real time: 71.512 sec; CPU: 164.809 sec


And here's the (truncated) output from souporcell.log:

WARNING: Logging before flag parsing goes to stderr.
W0725 01:26:18.452565 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:99: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable i$

W0725 01:26:18.581297 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:100: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder in$

W0725 01:26:18.608251 140522349819264 deprecation.py:323] From /opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:2403: add_dispatch_support.<locals>.w$
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0725 01:26:18.616338 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:117: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.$

W0725 01:26:18.821783 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:125: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto in$

W0725 01:26:18.822011 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:130: The name tf.global_variables_initializer is deprecated. Please use tf.compat.$

W0725 01:26:18.822538 140522349819264 deprecation_wrapper.py:119] From /opt/souporcell/souporcell.py:134: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-25 01:26:18.826168: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-25 01:26:18.915307: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000074999 Hz
2019-07-25 01:26:18.917488: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560cabc6c440 executing computations on platform Host. Devices:
2019-07-25 01:26:18.917559: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-25 01:26:18.986166: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_glo$
loci being used based on min_alt, min_ref, and max_loci 0


It may be worth noting that the data may not be sequenced at sufficient depth (according to other ISSUE threads I've perused). I'm using a parsed cell barcode list corresponding to cells that passed my QC standards (i.e., removing apoptotic cells, removing doublets called using DoubletFinder, etc.), and these singlets are associated with an average of 5207 UMIs (notably, this corresponds to ~50K average reads, which is standard depth for 10x experiments).

Any thoughts? I really appreciate all of the help.
Chris

**Comment by wheaton5** [comment]
Ok. I think that this number of UMIs is low but souporcell should still be able to do something. I have another user over email with 4.6k median UMIs/cell on a human sample and she is getting moderate results and I am working with her on how to get better results. But in any case, getting 90% doublets (50k reads and 5k UMIs) seems like either your cells have low expression or for some reason the library prep efficiency wasn't very good. This other user has 200k reads/cell and only 4.6k UMIs/cell. I do not recommend you send the sample back for sequencing, because the vast majority of reads you sequence past what you have will also be dups. I may talk to my friends at 10x or other ppl knowledgable about the biochemistry about how common this is and what the causes are. Still, this should be enough for souporcell to do something with. Also could you let me know how many cells you have and how big souporcell_minimap_tagged_sorted.bam is  so ls -lah souporcell_minimap_tagged_sorted.bam. Also maybe the number of mapped reads. Easiest way is go into python then (you will need pysam, so pip install pysam, but you can also probably do this through my container)
```
import pysam
bam=pysam.AlignmentFile("souporcell_minimap_tagged_sorted.bam")
bam.mapped
```

could you tell me how many variants are in the freebayes output. So
zcat souporcell_merged_sorted_vcf.vcf.gz | grep -v '#' | wc -l
inside the souporcell run directory. Unfortunately I clean up the intermediate freebayes outputs so we can't see those. I assume vartrix isn't lying about 0 variants.

**Comment by chris-mcginnis-ucsf** [comment]
Cells are human PBMCs so not too surprising that the UMIs are fairly low (lymphocytes are pretty small). Also, I was providing info from the aggregated CellRanger output -- I only want to run souporcell on one of my 10x lanes (i.e., one where I pooled multiple PBMC donors), so the numbers I provided were slightly off. The mean reads/cell is ~125K and the read mapping rate from CellRanger output is 92.1%.

To address your questions, I used a list of 3432 cell IDs (with aggregated lane suffixes removed to fit with the unaggregated BAM files), and the souporcell_minimap_tagged_sorted.bam is 37K (this seems pretty small, no? The original size of the possorted_genome_bam.bam file is 35G). After running your mapped reads code, this seems to be the issue -- bam.mapped output is 0.

One issue I could see that would cause the lack of mapping is that I first aligned my fastqs to a different reference than I used in my souporcell run. I used the hg19-3.0.0 reference from CellRanger for my initial alignment, but used the GRCh38 because I kept getting errors trying to use my original reference in souporcell.  I will try again with the hg19-3.0.0 reference to recreate the error and report back.

Chris

**Comment by wheaton5** [comment]
Ok. Yes. 0 reads is a problem lol. Are you giving souporcell the origininal bam file? If you remapped to something else without reattaching barcodes and UMIs and then fed that to souporcell, that would be a problem as souporcell only keeps reads with cell barcode tags and UMI tags.

This is the first thing to check.

**Comment by chris-mcginnis-ucsf** [comment]
Pipeline completed successfully! Turned out I had a "-1" suffix in my BAM file that was not included in my provided list of cell IDs. Thanks for the help!
