### ISSUE TITLE
Failing to pick up a genotype in single-genotype sample

### ISSUE THREAD

**Issue by ktpolanski** [wheaton5/souporcell#31]
Hello, me again, sorry. A mixed donor experiment happened, and I'm trying to run souporcell on it. The biologist's design felt quite elegant - 36 samples with the same two donors mixed, and then in order to recover which donor is which a separate one with just one donor in it. However, when I process the single donor sample with souporcell I get a `cluster_genotypes.vcf` an order of magnitude shorter than the other samples, and made up of straight `./.` calls. This is with an artificial k of 2, after getting a similar result with k set to 1.

Any idea how to proceed here? Should I artificially merge the BAM with another sample's BAM? Or is there something that can be done on a single sample level to rescue this?

**Comment by wheaton5** [comment]
I will have to look into the single sample issue. As for matching up clusters from the other multiple 2-sample datasets, we have a script shared_samples.py. 

But I realize this doesn't fully solve your problem. You not only want to know which clusters represent the same samples, but which samples those are. And a single sample experiment should give you that information. But I didn't design souporcell for single sample datasets. I think you could just run freebayes on that single sample and feed that vcf along with the mixed sample vcfs (one at a time) to the shared_samples.py script?

**Comment by ktpolanski** [comment]
Eh, I should be able to take it from here. I made a shared BAM, taking the one-donor sample and adding a prefix to the start of each cell barcode to avoid duplicates, then merging it with another BAM. I should be able to use that as a reference in `shared_samples.py` and match things up quite nicely. Thanks!

Single donor support would be nice at some point, but isn't high priority.
