### ISSUE TITLE
conceptual problems with scATAC-seq application?

### ISSUE THREAD

**Issue by ktpolanski** [wheaton5/souporcell#32]
Hello, sorry, me again. This time with a general inquiry - there's some scATAC-seq coming in a project I'm working on, and it'll also need donor deconvolution. I assessed the incoming data from a technical angle, and the BAM/barcode list should be acquirable. However, a collaborator raised a concern with regards to souporcell's use of soup in its modelling. There is no soup in scATAC-seq. However, we've been so happy with the output of souporcell on our transcriptomics data that it'd be great to use the algorithm here if possible.

Do you have any thoughts on the matter? Sorry if this is a dumb question, I'm a complete scATAC-seq greenhorn.

**Comment by wheaton5** [comment]
Hi. Glad you have had good experiences. The lack of soup should not be a problem. And I have had users use souporcell for scATACseq. Also the explicit soup modeling is only in the genotyping and ambient rna estimation step which is the last step. The other steps have just been designed to be very resilient to ambient rna. I think there might need to be some file format munging to make it work tho. But if you need help just ask me. I should add full support for scATACseq with no work by the user.

**Comment by ktpolanski** [comment]
Awesome, thanks a lot! :)
