### ISSUE TITLE
Change Barcode Identifier

### ISSUE THREAD

**Issue by drneavin** [wheaton5/souporcell#37]
Hi @wheaton5,

I am wondering if there is a way to indicate a different barcode identifier and UMI identifier other than CB and UB? I recently ran into this issue and have altered the bam file to replace all the barcode indicators and UMI indicators with CB and UB but it would be good to have this option instead of editing the bam file directly. Let me know if there is already this option which I have missed.

**Comment by wheaton5** [comment]
Sure, I am addressing several requests this weekend and this is an easy one to throw in. Will update here when completed.

**Comment by drneavin** [comment]
Great, thanks @wheaton5! I’ll look forward to your update

**Comment by wheaton5** [comment]
--umi_tag option now available

**Comment by wheaton5** [comment]
@drneavin closing this now, reopen if you have issues.

Best,
Haynes
