### ISSUE TITLE
Pipeline warnings (scRNA-seq)

### ISSUE THREAD

**Issue by annamath** [wheaton5/souporcell#39]
Hello! 

I used the souporcell pipeline for demultiplexing genotypes of a scRNA-seq dataset consisted of 3 individuals. The dataset was produced with 10x Genomics (v3).

`singularity exec souporcell.sif souporcell_pipeline.py --bam /data/sample1_counts/HNTLNBGXC/outs/possorted_genome_bam.bam --out_dir /sample1_genotype_souporcell/ --fasta /data/refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa --common_variants /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf --barcodes /data/barcodes.tsv --threads 8 --clusters 3 --ploidy 2 --skip_remap SKIP_REMAP `

I demultiplexed the same dataset using cellSNP (for variant calling) and then vireo. The overlap of cells identified per individual is quite big in both approaches.

Although, I am getting the messages bellow at the end of the pipeline:

> 156515 excluded for potential RNA editing
> 562 doublets excluded from genotype and ambient RNA estimation
> 6424 not used for soup calculation due to possible RNA edit
> /usr/local/envs/py36/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   elif np.issubdtype(np.asarray(v).dtype, float):
> Initial log joint probability = -573687
>     Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
> Exception: log_mix: lambda1 is -nan, but must not be nan!  (in 'unknown file name' at line 73)
> 
> Exception: log_mix: lambda1 is -nan, but must not be nan!  (in 'unknown file name' at line 73)
> 
> Exception: log_mix: lambda1 is -nan, but must not be nan!  (in 'unknown file name' at line 73)
> 
> Exception: log_mix: lambda1 is -nan, but must not be nan!  (in 'unknown file name' at line 73)
> 
> 
>        6       -144057    0.00346277      0.918425           1           1       27   
> Optimization terminated normally: 
>   Convergence detected: relative gradient magnitude is below tolerance
> done
> 

So, my question is if I should just ignore this, considering that the pipeline finished and gave me results that I can also validate with an alternative approach. 
Or there is something that needs to get fixed in order to avoid these messages? 

Thank you very much in advance : )

Best, Anna

**Comment by wheaton5** [comment]
All of those warnings are normal. I know it may seem bad, but the STAN random initialization sometimes causes NaN values, but it just reinitializes. It is possible that I could set constraints on initialization to cause this not to happen, but despite this it works very consistently. I would ignore this. For me in the future I may want to tighten that step up.
