### ISSUE TITLE
IndexError: index 12009 is out of bounds for axis 0 with size 10333

### ISSUE THREAD

**Issue by notimenocall** [wheaton5/souporcell#4]
Hi,

Thanks for the great tools.
I am trying to run it for the 1st time and the script is killed when running running souporcell clustering. The error message is below:
`running freebayes
merging vcfs
running vartrix
running souporcell clustering
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 295, in <module>
    "-t",str(args.threads), "-l", args.max_loci, "--min_alt", args.min_alt, "--min_ref", args.min_ref,'--out',cluster_file],stdout=log,stderr=log)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['souporcell.py', '-a', 'sample1_souporcell/alt.mtx', '-r', 'sample1_souporcell/ref.mtx', '-b', 'barcodes.tsv', '-k', '2', '-t', '8', '-l', '2048', '--min_alt', '10', '--mi
n_ref', '10', '--out', 'sample1_souporcell/clusters_tmp.tsv']' returned non-zero exit status 1.
`
The souporcell.log says:
`loci being used based on min_alt, min_ref, and max_loci 54
Traceback (most recent call last):
  File "/opt/souporcell/souporcell.py", line 84, in <module>
    cell_data[cell-1][index] = float(ref_c)/float(ref_c+alt_c)
IndexError: index 12009 is out of bounds for axis 0 with size 10333
`

Any idea what went wrong? Thanks much!

**Comment by wheaton5** [comment]
Hi,

Thanks for your interest. Looking at the code, the only way this could happen is if some cells have 0 loci with variants. I should have imagined this happening. I will post here when I have a tested solution. 

But also this is somewhat concerning regarding your data. Are you sure you are using just the cell barcodes from cellranger? How many lines are in your barcodes.tsv file? If you look at the summary.html from cellranger, what is the number of reads per cell and number of UMIs per cell and the number of genes per cell?

Best,
Haynes

**Comment by notimenocall** [comment]
Hi,

Thanks for your prompt reply.
Does it suggest the cells have not enough reads/cell and that's why 0 loci were found? This data set is actually shallowly sequenced. I used it since it is small for testing. Is there a recommendation for minimally how many reads per cells are required for proper demultiplexing? Or have you tested down sampling the reads and see how the accuracy drops? Sorry if I missed this from your manuscript. Thanks much!

**Comment by wheaton5** [comment]
Not a problem. This is an issue that should be fixed so I thank you for your post. I have not downsampled reads to test this. That would be a good thing to do. But certainly the fewer reads you have per cell will decrease the signal to noise (and if the signal is 0, the signal is 0 lol). Glancing at my supplemental tables, for human my samples had 18k-25k median UMIs per cell and while I don't think I have this recorded in the preprint, that corresponded to around ~90k (don't quote me on that) reads per cell. For the plasmodium we had far fewer UMIs per cell, but the transcriptome is much smaller, variants more frequent, and it is a haploid organism. Even so the signal to noise was very low for those samples. I hope this helps. I will try to reproduce this and create a fix, but it may take a few days. I should also have some guidelines on this with warnings/errors built into the system.

Cheers,
Haynes

**Comment by notimenocall** [comment]
Hi Haynes,
Thanks for the reply! I tried again on another human PBMC data set with 17,840 mean reads per cells and it worked perfectly. The data set was also antibody hashed. Amazing close to 100% agreement between the two methods. Great work!

**Comment by wheaton5** [comment]
That is great! Reopening this issue just to remind myself to fix the legit bug you did find. Will close when fixed.

Cheers,
Haynes

**Comment by wheaton5** [comment]
fixed with https://github.com/wheaton5/souporcell/issues/16
