### ISSUE TITLE
TCR/BCR data

### ISSUE THREAD

**Issue by arutik** [wheaton5/souporcell#40]
Hello,

Can souporcell deconvolute TCR/BCR data (out of cellranger-vdj)?

Thank you.

Sincerely,
Anna Arutyunyan

**Comment by wheaton5** [comment]
I am really not very familiar with the data. If there are enough SNP locations in the data and enough UMI/cell then I would expect it to work. There may be some formatting issues involving the barcode/umi tags that might have to be dealt with. 

Best,
Haynes

**Comment by arutik** [comment]
Thank you, got it. I guess an easier option would be to do TCR/BCR sequencing from the split library with the same UMIs as in the main scRNA-seq.
Closing the issue.

Sincerely,
Anna Arutyunyan
