### ISSUE TITLE
souporcell_pipeline.py :: run souporcell from path

### ISSUE THREAD

**Issue by EricDeveaud** [wheaton5/souporcell#42]
Hello, 

souporcell_pipeline.py runs rust compiled souporcell binary with and absolute path 
please use a call to souporcell from user path, as it is done for troublet 

what is done for supporcell binary
``` 
souporcell_pipeline.py:            cmd = [directory+"/souporcell/target/release/sou
porcell", "-k",args.clusters, "-a", alt_mtx, "-r", ref_mtx
```

versus what is done for troublet binary

```
souporcell_pipeline.py:        subprocess.check_call(["troublet", "--alts", alt_mtx
, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub)
```

best regards 
Eric

**Comment by wheaton5** [comment]
Thanks for catching this. I will change it. Of course you can work around it by adding troublet to your path for the time being.

**Comment by EricDeveaud** [comment]
it's what I've done.
hacked souporcell_pipeline.py to call `souporcell` from the path 

here is  the change I've made
```
sed -i -e 's|directory.*souporcell"|"souporcell"|' souporcell_pipeline.py
```

regards

Eric
