### ISSUE TITLE
Known Genotype Rerun

### ISSUE THREAD

**Issue by drneavin** [wheaton5/souporcell#44]
Hi @wheaton5 , I am interested in using the `--known_genotypes` and` --known_genotypes_sample_names` options for some souporcells runs that I have already done.

I am wondering when the known genotypes are used so I can just delete the files from that step forwards and I don't have to rerun the entire pipeline. I would think that it would be at the clustering step? So I would just have to remove the following files and rerun with those additional parameters?

```
clusters.err
clusters_tmp.tsv
clustering.done
doublets.err
clusters.tsv
troublet.done
ambient_rna.txt
consensus.done
cluster_genotypes.vcf
```

Let me know if this is how you would go about rerunning souporcell with known genotypes without having to start from the beginning. Thanks for your help!

Cheers,
Drew

**Comment by wheaton5** [comment]
Well, it is used both for variant calling (it only calls variants at known genotype sites) as well as the clustering step. But deleting the .done files (any outputs will just be overridden if you delete the .done files) back to either freebayes or just clustering (I have not tested doing the later tho). Yes the .done files listed should work (but again not tested). The tested version i think would be deleting consensus.don, troublet.done, clustering.done, vartrix.done, and variants.done.

Best of luck.

Also for speed when using known_genotypes or common_variants you can use the --skip_remap True option which will greatly speed things up when running from scratch.

**Comment by drneavin** [comment]
Thanks @wheaton5! I'm also running into a problem where I have only a subset of my individuals genotyped in the pool and it throws an error since the -N does not match the number of individuals in the list. I have two questions:
1) Is there a way to fix this?
2) If I change the N to match the number of genotyped individuals in the pool, is souporcell going to call all the cells from individuals that were not genotyped as doublets? Or will it negatively impact the prediction of those that were genotyped?

Thanks for your help on this!

-Drew

**Comment by wheaton5** [comment]
1. Not as the current code stands. I coooould extend the feature to this where it would seed a subset of the clusters with known genotypes and would seed the others randomly. I am somewhat wary of scope creep here. How common do you think this situation will be?
2. Depends on where the genotypes fall in the high dimensional space and which loci each cell have data for. I think there will be a mix of incorrect cluster assignments and doublet assignments. 

I really built souporcell for the case in which you don't have genotyped individuals and added --known_genotypes after the fact. It just so happened that demuxlet had some serious biases which led me to believe in some cases for this problem an uninformed prior is better than a false or biased prior. If this is the case maybe you should run it without --known_genotypes? Were there problems you found with the clusterings without --known_genotypes?

Best,
Haynes

**Comment by drneavin** [comment]
1) My guess is that this will be relatively common. We have already had this happen for two independent projects largely because we ran out of material for genotyping or the samples failed genotyping QC due to missingness or other reasons. 

I think the best solution based on your response will probably be for each individual user who might have this situation to use the vcf that is output for each cluster at the end and match that to the known genotypes to identify the likely donor for each cluster.
