### ISSUE TITLE
souporcell singularity recipe :: may fail regarding singularity version

### ISSUE THREAD

**Issue by EricDeveaud** [wheaton5/souporcell#45]
Hello, 

FYI due to https://github.com/sylabs/singularity/issues/3401

building the container fail with singularity 3.5.2 due to 
```
%post -c /bin/bash
```

OK with singularity 3.4.0 and 3.5.3 not tested with 3.2* 

regards

Eric

**Comment by wheaton5** [comment]
Do you know of a fix? I don't feel like I need to support all versions of singularity.

**Comment by EricDeveaud** [comment]
using plain sh for the `%post` section ;-)
