### ISSUE TITLE
AssertionError: retag subprocess ended abnormally with code 1

### ISSUE THREAD

**Issue by onurdanaci** [wheaton5/souporcell#5]
Hi,

I have my code (for 10 different samples, 10 different ones are running parallel by changing the number as in 1-RNA*):

singularity exec /projects/ucar-lab/danaco/Software/Soupour/souporcell.sif souporcell_pipeline.py\
 -i /projects/ucar-lab/danaco/lawlon/PBMC_scRNAseq/BAM_Files/1-RNA_pooled_and_merged_Cellranger_Out_50k/outs/possorted_genome_bam.bam\
 -b /projects/ucar-lab/danaco/PBMC_scRNAseqv/GroundBarcodes/1-HTO.all.cell.barcodes.for.demuxlet.txt\
 -f /projects/ucar-lab/danaco/Software/Soupour/GRCh38_full_analysis_set_plus_decoy_hla.fa\
 -t 8 -o /projects/ucar-lab/danaco/Ground/Soupor/1-RNA -k 4

After running for all the different stages through the pipeline for 56 hours, threw an error at this UMI stage:

checking modules
imports done
checking bam for expected tags
no bam index found, creating
checking fasta
creating chunks
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
cleaning up tmp fastqs
repopulating cell barcode and UMI tags

Such that I get the error:

AssertionError: retag subprocess ended abnormally with code 1

**Comment by wheaton5** [comment]
Sorry about this. How big are your files? What are currently the files in the output directory and how big?

Perhaps you should get one sample through before attempting 10 in parallel. And if this is many cellranger runs pooled, maybe try to get one through before attempting the pooled sample.

I probably need to provide a new container that spits stdout and stderr of that process to a log file. I'll do that and get back to you.

**Comment by wheaton5** [comment]
Also I am making a version with options --skip_realign and --common_variants which would speed up your process significantly. Also I am implementing a dynamic restart of the same pipeline (it will use the output of steps it previously completed). I will test this over the weekend and put it up on/by Monday. I also have plans for speeding up the clustering process, but want to do significant tests on that before release.

**Comment by wheaton5** [comment]
New version now released with --skip_remap and --common_variants. See README or release page for new download links.

If your dataset has 50k cells we may also need to make some changes to clustering to speed up (either batch/stochastic gradient descent or and option for expectation maximization). Let me know if speedups to clustering are necessary for your use case. I am committed to making every user successful if possible. 

Best,
Haynes

**Comment by onurdanaci** [comment]
Hi,
Thanks for the answers and your commitment. I have 10 different datasets/samples and each of them have around 30k cells. Each of my possorted bam files are around 170-200 gb.

But, it's ok I parallelize because each of these 30k pbmc's are from different persons.
I will submit one of my samples to cluster with the new container, and will see how it goes. I will keep you up-to-date regarding the process.
Best,
Onur

**Comment by wheaton5** [comment]
That is quite a dataset!

So that I understand, each 30k pbmc's are from a single individual, and the 10 different datasets are different individuals? If that is the case, I don't understand what your use case for souporcell is. If each 30k pbmcs are a mixture of different individuals then I see the point. Could you give me some more details about the experimental setup?

Thanks,
Haynes

**Comment by onurdanaci** [comment]
Hi Haynes,

You are absolutely correct. We have 10 different individuals, more or less 30k pbmcs from each, and for each of the individuals (depending on treatment conditions they are subjected to) there is a hashtag oligo attached to them.

Yet, I am currently testing/benchmarking all the available doublet detection and demultiplexing softwares on our known singlets and doublets from HTO to see how well they are doing.

Best,
Onur

**Comment by wheaton5** [comment]
Ah, so I don't think souporcell is the right thing for you. Souporcell can only detect intergenotypic (cross-individual) doublets. If each individual was done in a separate 10x inlet, there will be 0 intergenotypic doublets. Does this make sense? I guess you could do a synthetic mixture and confirm that you see 0 doublets. Or you could do a synthetic mixture in which you combine some cross sample barcodes into one barcode and confirm that souporcell calls the sythetic doublets as doublets (this is something we do in our manuscript).

**Comment by wheaton5** [comment]
I am closing this thread because I think we have identified the issue which is that souporcell doesn't solve your use case. Please feel free to reopen or let me know if there are further issues.

**Comment by cdelacalle** [comment]
Hello! I am also getting this error also,

All good.... until: 
repopulating cell barcode and UMI tags
False
False
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 579, in <module>
    retag(args, minimap_tmp_files)
  File "/opt/souporcell/souporcell_pipeline.py", line 304, in retag
    assert not(p.returncode), "retag subprocess ended abnormally with code " + str(p.returncode)
AssertionError: retag subprocess ended abnormally with code 1

I have 10x reactions, 5 donors each, total of 20k cells (around 4k cells / donor).

**Comment by wjzwjz5** [comment]
Hi, I have the same error,

singularity exec --bind /database Demuxafy.sif souporcell_pipeline.py -i /database/possorted_genome_bam.bam -b /database/barcodes.tsv -f /database/fastq/220604A1-BCR_S1_L001_R1_001.fa -t 50 -o /database/res_0604A1_souporcell -k 6 --known_genotypes /database/VCF/out.vcf --known_genotypes_sample_names e3004A  e3170A  e3172A  e3239A  e3242A  e3243A

checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory /database/res_0604A1_souporcell
repopulating cell barcode and UMI tags
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_0.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_0.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_1.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_1.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_2.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_2.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_3.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_3.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_4.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_4.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_5.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_5.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_6.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_6.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_7.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_7.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_8.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_8.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_9.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_9.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_10.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_10.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_11.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_11.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_12.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_12.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_13.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_13.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_14.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_14.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_15.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_15.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_16.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_16.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_17.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_17.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_18.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_18.bam
False
False
retag.py --sam /database/res_0604A1_souporcell/souporcell_minimap_tmp_19.sam --no_umi False --umi_tag UB --cell_tag CB --out /database/res_0604A1_souporcell/souporcell_retag_tmp_19.bam
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 581, in <module>
    retag(args, minimap_tmp_files)
  File "/opt/souporcell/souporcell_pipeline.py", line 306, in retag
    assert not(p.returncode), "retag subprocess ended abnormally with code " + str(p.returncode)
AssertionError: retag subprocess ended abnormally with code 1

I have 10x reactions, 6 donors and total of 45k cells .
