### ISSUE TITLE
No such file or directory: 'renamer.py': 'renamer.py'

### ISSUE THREAD

**Issue by dwkarjosukarso** [wheaton5/souporcell#53]
Hi again,
I am trying it out in conda (using the yaml env) since singularity gave me an error and I am not familiar with it.

I ran the following command
`/pathTO/souporcell/souporcell_pipeline.py -i $bam -b $.txt -f $fa -t 4 -o /pathTO/outDIR/ -k 5`

and got this error:
```
Traceback (most recent call last):
  File "/home/karjosukarso/souporcell/souporcell_pipeline.py", line 528, in <module>
    (region_fastqs, all_fastqs) = make_fastqs(args)
  File "/home/karjosukarso/souporcell/souporcell_pipeline.py", line 209, in make_fastqs
    "--umi_tag", args.umi_tag, "--cell_tag", args.cell_tag])
  File "/home/karjosukarso/anaconda3/envs/souporcell/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/karjosukarso/anaconda3/envs/souporcell/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'renamer.py': 'renamer.py'
```

I check the git cloned souporcell dir and renamer.py is there

input BAM:
```
NS500173:399:HJ2MCBGX5:3:13509:20731:3554    16 chr1    86310   11      63M     *       0       0       TTGACTTTTGAACATACTTGGACTACATACCATTGCTTGAAAAAATAAAATATCTGCAAAATA <EEEEEE<EAEEEEEEEAEEAE/EAEEEEEEEEAEEAEEEAEEEEEEEEEEEEEEEEEAAAAA        CB:Z:TCCTAGCT_TAATCG    UB:Z:TGTAAGGG   MD:Z:61A1       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 XS:i:-15        YT:Z:UU
NS500173:399:HJ2MCBGX5:1:12303:4069:7998     16 chr1    87535   11      63M     *       0       0       TTTTTTATTTTTTAAAAAATTGCTAATTTACAGAACATGGAGATGAGTATGTTTTGAAGGCCC EEEEEEEEEEEEAEAAA<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA        CB:Z:TGGTTGTC_TACAGC    UB:Z:TGCCTACC   MD:Z:61T0T0     XG:i:0  NM:i:2  XM:i:2  XN:i:0  XO:i:0  AS:i:-10        XS:i:-20        YT:Z:UU
N
```

Do you probably know what went wrong?
Thanks,
Dyah

**Comment by wheaton5** [comment]
Yeah, I need to fix this. Sometimes I didn't include the directory of the script in the call because in my setup and in the singularity container I have that directory on the PATH so I overlooked it.

I'll fix this, but what you can do for the time being is add this to your ~/.bashrc
export PATH=/pathTO/souporcell:$PATH
and then back on the command line run source ~/.bashrc

**Comment by wheaton5** [comment]
I made the appropriate changes but have not tested yet.

**Comment by wheaton5** [comment]
There may be more issues now that I think about it. This way of running it I haven't tested very thoroughly on a fresh computer.

You will also need Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
and you will need to compile the rust code
so go to /pathTo/souporcell/souporcell/
and run
cargo build --release
and go to /pathTo/souporcell/troublet/
and run
cargo build --release

I'll try to think if i left anything else out of the README for this setup. I'll add these things to the README now.

**Comment by wheaton5** [comment]
closing issue. reopen if you are still having problems.
