### ISSUE TITLE
version `CURL_OPENSSL_4' not found

### ISSUE THREAD

**Issue by afcmalone** [wheaton5/souporcell#58]
Hi,
I am having an issue running the 'singularity exec' command as i get the error:

ImportError: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /home/humphreys/.local/lib/python3.6/site-packages/pysam/libchtslib.cpython-36m-x86_64-linux-gnu.so)

I am using ubuntu 18.04.
Linux humphreys-HP-Z820-Workstation 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I hear there are many issues with libcurl3 and 4 on ubuntu but cant solve them.
any ideas?

Thanks

**Comment by wheaton5** [comment]
Ummm, I don't understand why this would be looking in your .local/lib/python packages. I don't understand all of this stuff fully, but it should be loading pysam from the singularity container which should have everything except the OS kernel included. Singularity should not even see directories upstream of the working directory from which it was run. Can you give me the command you are running and the directory from which you are running it?

Can you try  singularity exec souporcell.sif python
then when the python terminal comes up
import pysam

Do you get the same error?

**Comment by afcmalone** [comment]
Hi,
Thanks for your email. In the end i decided to clean up my machine and
reboot. this seemed to do the trick
Thanks
Andrew
