### ISSUE TITLE
barcodes.tsv.gz

### ISSUE THREAD

**Issue by drneavin** [wheaton5/souporcell#68]
Hi @wheaton5,

I am using some 10x datasets that have been processed on cellranger v3 so all the input files are gzipped. I am getting an error when I try to run souporcell that I think may be because it expects non-gzipped files?:

```
checking modules
imports done
checking bam for expected tags
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 63, in <module>
    for (index, line) in enumerate(barcodes):
  File "/opt/conda/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

Would you consider including support for gzipped files since cellranger v3 outputs the matrix files as gzipped?

Let me know if you think this is a different issue and not due to gzipped files.

Thanks,
Drew

**Comment by wheaton5** [comment]
You are correct. Seems they have switched to gzipping the barcodes.tsv file. This isn't the matrix, but just the list of cell barcodes which is quite small. I will add support for optionally gzipped files. In the mean time you can just gunzip the barcodes.tsv.gz and rerun. Sorry about this.

**Comment by drneavin** [comment]
Thanks @wheaton5, I have just copied the barcodes file to an unzipped version for now. Thanks for adding in the functionality! Much appreciated.

**Comment by drneavin** [comment]
Hey @wheaton5 , any update when this will be implemented?

**Comment by wheaton5** [comment]
Sorry. It is implemented except unfortunately vartrix requires unzipped barcode file so I can't just option open zip/nonzip. I have to unzip into the output directory anyway. This is implemented I just didn't deploy it yet. I'll get that done in the next 2 days (tomorrow is busy). Best,
Haynes

**Comment by drneavin** [comment]
Thanks @wheaton5! a bit funny that vartrix hasn't been updated to use both zipped and unzipped files since it's 10x software

**Comment by wheaton5** [comment]
Now supported. Sorry for the delay. The release kept getting more things added to it as more people reported issues.

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tj2j8QZuGz8sylHgWbnejWyUn8n6m0Y8' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tj2j8QZuGz8sylHgWbnejWyUn8n6m0Y8" -O souporcell.sif && rm -rf /tmp/cookies.txt
