### ISSUE TITLE
Could not retrieve index file for A.Merged.Bam

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [wheaton5/souporcell#70]
Thank you for his amazing package.
I got error here. 
Even though I check the file size to make it is intact, I still got error

> [E::idx_find_and_load] Could not retrieve index file for 'A.merged.bam'
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
samtools index: failed to create index for "A.merged.bam"
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory demux_data_test
no bam index found, creating
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 528, in <module>
    (region_fastqs, all_fastqs) = make_fastqs(args)
  File "/opt/souporcell/souporcell_pipeline.py", line 176, in make_fastqs
    subprocess.check_call(['samtools', 'index', args.bam])
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['samtools', 'index', 'A.merged.bam']' returned non-zero exit status 1.

**Comment by XiaofeiSunUCSF** [comment]
Fixed!

**Comment by ZebinWen** [comment]
May I ask how you fixed it? Cause I meet the same problem and I found that the souporcell_pipeline.py stopped halfway

**Comment by luostrowski** [comment]
I'm having the same problem. Would you have any suggestions on how to fix it? @XiaofeiSunUCSF

**Comment by wheaton5** [comment]
samtools index A.Merged.Bam
