### ISSUE TITLE
Using a subset of cell barcodes

### ISSUE THREAD

**Issue by sylvia-science** [wheaton5/souporcell#75]
Is it valid to input only a subset of cell barcodes? I'd like to run the program only on cells that have passed my quality control and are now labeled. 

I know I'll have to run it with --ignore True to pass the barcode check. I just want to make sure that the downstream .mtx files will have the same column order as the input barcodes.

**Comment by wheaton5** [comment]
That is fine. You probably won't have to use --ignore True unless it is a small subset of the barcodes. It just makes sure that some reasonable % of reads have listed barcodes.
