### ISSUE TITLE
VCF files cover only parts of the chromosomes

### ISSUE THREAD

**Issue by vertesy** [wheaton5/souporcell#76]
Hey,

thanks for the great tool! We are very excited to try it out.

Nevertheless, we encountered a problem that VCF files cover only parts of the chromosomes, when using SoC from your singularity container:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5101911/91875508-d791a380-ec7b-11ea-9928-96bbf3e4fb6a.png">
I loaded the VCFs in IGV (2 experiments with 2 and 2 genotypes)

We think that this is because freebayes is called `-r 1:206651952-248956422` parameter (I can see in VCF file header).  This is the exact region that has the coverage in IGV `chr1:206,651,952-248,956,422`.

Looking at all chromosomes, it is clear that the `end` coordinate is fine, just `start` is wrong.

Defined in [line 448:](https://github.com/wheaton5/souporcell/blob/3fb3dde901e5f946f2ed9a47e9dbc4e1664f0c99/souporcell_pipeline.py#L448)
`                cmd.extend(["-r", chrom + ":" + str(start) + "-" + str(end)])`
that is defined in ` start = region[sub_index][1]`,
which is then defined somehow during the paralallelization (?).

Could you help with this issue either by debug it or how to disable parallelization  ?
[Maybe I am wrong blaming parallelization]

Thanks a lot & lookng fwd!

#### VCF header

```xml

##fileformat=VCFv4.2
##fileDate=20200827
##source=freeBayes v1.3.1-dirty
##reference=genome.fa
##phasing=none
##commandline="freebayes -f genome.fa -iXu -C 2 -q 20 -n 3 -E 1 -m 30 --min-coverage 44 --pooled-continuous --skip-coverage 100000 -r 1:206651952-248956422 souporcell_k2/souporcell_minimap_tagged_sorted.bam"
##bcftools_concatVersion=1.9+htslib-1.9
##bcftools_concatCommand=concat souporcell_k2/souporcell_2_0.vcf souporcell_k2/souporcell_3_0.vcf souporcell_k2/souporcell_5_0.vcf souporcell_k2/souporcell_6_0.vcf souporcell_k2/souporcell_7_0.vcf souporcell_k2/souporcell_8_0.vcf souporcell_k2/souporcell_9_0.vcf souporcell_k2/souporcell_10_0.vcf souporcell_k2/souporcell_11_0.vcf souporcell_k2/souporcell_12_0.vcf souporcell_k2/souporcell_14_0.vcf souporcell_k2/souporcell_15_0.vcf souporcell_k2/souporcell_16_0.vcf souporcell_k2/souporcell_18_0.vcf souporcell_k2/souporcell_20_0.vcf souporcell_k2/souporcell_21_0.vcf souporcell_k2/souporcell_23_0.vcf souporcell_k2/souporcell_25_0.vcf souporcell_k2/souporcell_26_0.vcf souporcell_k2/souporcell_27_0.vcf souporcell_k2/souporcell_29_0.vcf souporcell_k2/souporcell_11_1.vcf souporcell_k2/souporcell_15_1.vcf souporcell_k2/souporcell_27_1.vcf souporcell_k2/souporcell_27_2.vcf souporcell_k2/souporcell_27_3.vcf souporcell_k2/souporcell_27_4.vcf; Date=Thu Aug 27 02:28:04 2020
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
```

**Comment by wheaton5** [comment]
I fixed a problem like this several months ago and it was due to a bug in parallelization. When did you download this singularity container? You can try -t 1 to turn off threading and see if you get the same regions. I may well have another bug and if so I thank you for catching it. What is your command? Back when I fixed this (or a similar bug) I checked that I was covering the whole chromosomes with 8 and 64 threads. I guess I'll check that again now.

**Comment by vertesy** [comment]
Thanks for getting back so fast! We will try `-t 1`.

We downloaded the container a some days ago, and the command (as per info.txt) is:
```bash
container="~/containers/biosw/souporcell/202008/souporcell.sif"
nohup singularity exec $container souporcell_pipeline.py -i possorted_genome_bam.bam -b 124719_rnacount.filtered_feature_bc_matrix.124719.barcodes.tsv -f genome.fa -t 30 -o souporcell_k3 -k 3 --ploidy 2 &
```

**Comment by wheaton5** [comment]
Ah, so the previous bug was in the parallelization of the remapping, not the variant calling. Probably a bug... how can I be so bad at writing that type of thing? I'm testing now and will get it sorted soon.

**Comment by wheaton5** [comment]
I have found the bug and am near a final fix. Will update here when I have a new singularity build. Thanks for catching this. It will increase the signal to noise for everyone running in de novo mode (no common variants or known genotypes).

**Comment by vertesy** [comment]
Thanks a lot, that was really fast! Looking fwd!

**Comment by wheaton5** [comment]
Should be fixed in latest singularity build. Sorry for the delay. I had some presentations to give and my cluster's filesystem has been up and down.

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tj2j8QZuGz8sylHgWbnejWyUn8n6m0Y8' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tj2j8QZuGz8sylHgWbnejWyUn8n6m0Y8" -O souporcell.sif && rm -rf /tmp/cookies.txt

**Comment by vertesy** [comment]
Thanks Haynes, looks good now!

<img width="856" alt="image" src="https://user-images.githubusercontent.com/5101911/92461654-d0ade800-f1c9-11ea-8493-d584441c701a.png">
(gap is intergenic region as displayed in the bottom row)
<br>
<br>

### Comparing results:

- VCF file (cluster_genotypes.vcf) is 6 times bigger
- Interestingly cell assignment changed minimally (`cut -f 3 clusters.tsv  | sort | uniq -c | sort -nr`)
- We got very wild ambient RNA estimates before in 1 of the 2 datasets (40%) that is solved. New estimate ~16% is consistent with what  a SNP-independent method, SoupX guesses.

Other users, keep in mind that these numbers and improvements are for our case only. They are absolutely a function of sequencing depth and de-multiplexing complexity (Number of genotypes and their distance).

**Comment by wheaton5** [comment]
Thanks again for catching this and improving the tool for everyone. My apologies for the mistake.

**Comment by wheaton5** [comment]
"in most datasets, but massively changed in one of them (14765 > 7728 cells assigned to GT X)"
Do you believe this change is correct or incorrect?
