### ISSUE TITLE
How does souporcell handle missing genotypes in known_genotype vcf input?

### ISSUE THREAD

**Issue by mesnger** [wheaton5/souporcell#81]
Hello, again.

This is a followup question to #44 
I am currently pushing the loading cell limit for single cell sequencing using souporcell as the main deconvolution method. Now I am trying to speed up and automate the process by using known_genotypes.

I previously applied souporcell on patient derived xenograft samples(human and mouse cells combined) and successfully deconvoluted human and mouse cells, as well as identifying human/mouse doublets. But, as I do not know the genotypes for mouse sample, I could not use known_genotypes option on human/mouse pooled single cell data.

Do you recommend:
A. Perform WES on few mouse strains used in single cell and add the data to known_genotypes vcf.
B. If souporcell doesn;t ignore SNP sites with missing value, I could put a dummy sample ID in genotypes vcf for mouse with variants found from mouse dbsnp and fill all genotypes with missing (./.). Can souporcell call SNPs and cluster missing GT?

For clarification, the dummy vcf would look similar to this:
CHROM            ( ... ) FORMAT human1 human2 dummy3
GRCh38___chr1 ( ... ) GT                0/1       1/1          ./.
GRCh38___chr2 ( ... ) GT                1/1       0/0          ./.
GRCh38___chr3 ( ... ) GT                0/1       0/1          ./.
...
mm10___chr1    ( ... ) GT                ./.          ./.           ./.
mm10___chr2    ( ... ) GT                ./.          ./.           ./.
mm10___chr3    ( ... ) GT                ./.          ./.           ./.
...

Cheers,
mesnger

**Comment by katkoad** [comment]
You closed this, but I am having this issue and need information on what you did

**Comment by mesnger** [comment]
For the problem about deconvoluting human and mouse cells combined single cell data,
I compared other genotype-based method but found no success. So I devised other methods to separate mouse and human cells first, then used genotype-based methods for human-only, mouse-only data. The detailed method are currently accepted and is waiting to be published.  You can find the preprint version in www.biorxiv.org/content/10.1101/2021.04.04.438147v4

For the problem regarding the missing genotype, I came to a conclusion to not used known genetype option.
If you are having trouble finding a certain identity, i recommend changing the number of sample (-k option) value. When the unidentified identity has very small cell number compared to all cell counts, it may not form a large enough cluster to be called a single identity by souporcell. In few cases, I increased the k value to more than twice the number of identity I pooled and found a small number of cells (generally less than 500 cells) to match the missing identity I was looking for. Otherwise the identity may have not been sequenced (due to poor cell quality during library prep, or other unknown reasons).

**Comment by wheaton5** [comment]
Yeah, it doesn't make sense to use these methods for cross-species experiments. Deconvolving them should be easy by just mapping to a concatenated reference and ask for each cell "how many reads mapped to each genome". This was done in the original 10x genomics single cell paper.

**Comment by katkoad** [comment]
In case anyone else ends up coming across this, here is what I did. Souporcell will throw an error if the vcf file is missing genotypes (./. wont be accepted). I start with two separate VCF files, one for sample 1 and another for sample 2. When I merge the vcf files into one, I use bcftools merge with the -0 parameter, that fills in missing genotypes with some default value to make sure they arent empty. 

bcftools merge -0 -o merged.vcf sample1.vcf sample2.vcf
