### ISSUE TITLE
What is the versioning scheme of the souporcell?

### ISSUE THREAD

**Issue by mxposed** [wheaton5/souporcell#89]
What's the best way to refer to a specific version of souporcell?
Are older version still available, if I saved their wget google drive download scripts?

Thank you for the great tool

**Comment by wheaton5** [comment]
I should be better about this. I guess the only real way right now is commit hash. Mostly the former singularity builds are not available. But v1.0 is still available. And now the singularity build script is in the repo, so you could recreate that singularity image if you need to from a previous version.

**Comment by mxposed** [comment]
Thank you! Commit hash works for me. I hope what you tagged here as v2.0 is also available for download.
