### ISSUE TITLE
consensus.py: error: ambiguous option: --v could match --vcf_out, --vcf

### ISSUE THREAD

**Issue by brianpenghe** [wheaton5/souporcell#91]
I used this command:
`singularity exec -B $PWD ~/tools/souporcell/souporcell.sif consensus.py -c clusters.tsv -a alt.mtx -r ref.mtx --soup_out soup.txt --v ~/tools/souporcell/jbID.noGenotypes.vcf --vcf_out cluster_genotypes.vcf --output_dir .
`
But it said:
`usage: consensus.py [-h] -c CLUSTERS -a ALT_MATRIX -r REF_MATRIX [-p PLOIDY]
                    --soup_out SOUP_OUT --vcf_out VCF_OUT --output_dir
                    OUTPUT_DIR -v VCF
consensus.py: error: ambiguous option: --v could match --vcf_out, --vcf`

Then I used '-v' instead of '--v' and it seemed to work.

Guess the readme was not correct?
![image](https://user-images.githubusercontent.com/4110443/98868546-36d41700-2468-11eb-973e-d248940857f2.png)

**Comment by wheaton5** [comment]
Thanks. I'll fix the readme.
