### ISSUE TITLE
Support for Rhapsody output

### ISSUE THREAD

**Issue by annamath** [wheaton5/souporcell#96]
Hello,

I was wondering whether you've tried souporcell for Rhapsody output files or if you know whether it works? if not, are you planning to add this option. Thanks :) 

Anna

**Comment by domenico-somma** [comment]
Hello,
I am also interested to know if Rhapsody output (Whole transcriptome) is/will be supported or not.

Thanks

**Comment by Conorisco** [comment]
Also interested. New bioinformatics pipeline for rhapsody create outputs more silimar to 10X than previous revisions.
