### ISSUE TITLE
renamer.py scripts not found by subprocess.py

### ISSUE THREAD

**Issue by GAgafencu** [wheaton5/souporcell#97]
I have stumbled upon this particular error during the testing of supourcell:

Command:
(souporcell) [ggafencu@cbrglogin3 souporcell_test]$ python /t1-data/user/ggafencu/souporcell/souporcell/souporcell_pipeline.py -i A.merged.bam -b GSM2560245_barcodes.tsv -f /databank/10x-rangers/refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa -t 8 -o demux_data_test -k 4

Console output:
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory demux_data_test
generating fastqs with cell barcodes and umis in readname
Traceback (most recent call last):
  File "/t1-data/user/ggafencu/souporcell/souporcell/souporcell_pipeline.py", line 560, in <module>
    (region_fastqs, all_fastqs) = make_fastqs(args)
  File "/t1-data/user/ggafencu/souporcell/souporcell/souporcell_pipeline.py", line 217, in make_fastqs
    "--umi_tag", args.umi_tag, "--cell_tag", args.cell_tag])
  File "/home/molhaem9/ggafencu/.conda/envs/souporcell/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/molhaem9/ggafencu/.conda/envs/souporcell/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'renamer.py': 'renamer.py'

I went back and checked if renamer.py was found in the directory where I downloaded the Github repository and the renamer.py was there. I've installed souporcell using the conda method.

Any idea how should I debug this would be appreciated. 
Thank you for your time and help,
Grigore

**Comment by wheaton5** [comment]
i just put in a fix for this. you can pull latest and it should work

**Comment by GAgafencu** [comment]
Thanks a lot! It seems to be working!
