### ISSUE TITLE
genotype based demultiplexing

### ISSUE THREAD

**Issue by notimenocall** [wheaton5/souporcell#98]
Hi,
I am working with a data set where 4 donors are mixed into a single cell lane, of which 3 donors have genotype info but one doesn't. What would be your recommendation here? I see a huge discrepancy between results from Souporcell and demuxlet, which is not so surprising considering only genotype info from 3 donors was fed into demuxlet pipeline. Any advice from you will be greatly appreciated!

Thanks,
Xiao

**Comment by wheaton5** [comment]
I currently don't have it set up to be able to take a subset of known genotypes. I would expect demuxlet to most likely call almost all of the 4th individual's cells as doublets. In any case, souporcell works quite well with 4 donors even with pretty low UMI. I would just trust it, but I am biased lol.

**Comment by notimenocall** [comment]
You are right about the results. Thanks much for your thoughts!
